// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bordero struct {
	ID        pgtype.UUID
	EmpresaID pgtype.UUID
	Descricao string
	Status    string
	CriadoEm  pgtype.Timestamp
}

type Colaboradore struct {
	ID                      pgtype.UUID
	EmpresaID               pgtype.UUID
	Nome                    string
	Cpf                     string
	Cargo                   string
	Salario                 pgtype.Numeric
	DataAdmissao            pgtype.Date
	Status                  string
	FacialBiometriaTemplate pgtype.Text
	CriadoEm                pgtype.Timestamp
	AtualizadoEm            pgtype.Timestamp
}

type Comanda struct {
	ID                pgtype.UUID
	EmpresaID         pgtype.UUID
	NumeroMesaComanda string
	Total             pgtype.Numeric
	Status            string
	CriadoEm          pgtype.Timestamp
	AtualizadoEm      pgtype.Timestamp
}

type ComandaIten struct {
	ID             pgtype.UUID
	ComandaID      pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoUnitario  pgtype.Numeric
	StatusCozinha  string
	CriadoEm       pgtype.Timestamp
}

type ConfiguracoesBanco struct {
	ID                 pgtype.UUID
	EmpresaID          pgtype.UUID
	BancoNome          string
	ClientID           string
	ClientSecret       string
	CertificadoDigital pgtype.Text
	TokenAtual         pgtype.Text
	Status             string
	CriadoEm           pgtype.Timestamp
}

type ContasPagar struct {
	ID             pgtype.UUID
	EmpresaID      pgtype.UUID
	BorderopID     pgtype.UUID
	Descricao      string
	Valor          pgtype.Numeric
	DataVencimento pgtype.Date
	Status         string
	Origem         string
	OrigemID       pgtype.UUID
	DataPagamento  pgtype.Timestamp
	CriadoEm       pgtype.Timestamp
}

type ContasReceber struct {
	ID             pgtype.UUID
	EmpresaID      pgtype.UUID
	Descricao      string
	Valor          pgtype.Numeric
	DataVencimento pgtype.Date
	Status         string
	Origem         string
	OrigemID       pgtype.UUID
	DataPagamento  pgtype.Timestamp
	CriadoEm       pgtype.Timestamp
}

type Empresa struct {
	ID                  pgtype.UUID
	RazaoSocial         string
	Cnpj                string
	Nicho               string
	ModuloRh            pgtype.Bool
	ModuloKds           pgtype.Bool
	ModuloMesasComandas pgtype.Bool
	ModuloOrdemServico  pgtype.Bool
	ModuloGradeProdutos pgtype.Bool
	ModuloSelfCheckout  pgtype.Bool
	ModuloPontoFacial   pgtype.Bool
	Status              pgtype.Text
	CriadoEm            pgtype.Timestamp
	AtualizadoEm        pgtype.Timestamp
}

type EntradasEstoque struct {
	ID             pgtype.UUID
	EmpresaID      pgtype.UUID
	PedidoCompraID pgtype.UUID
	ChaveNfe       pgtype.Text
	XmlNfe         pgtype.Text
	CriadoEm       pgtype.Timestamp
}

type EntradasEstoqueIten struct {
	ID               pgtype.UUID
	EntradaEstoqueID pgtype.UUID
	ProdutoGradeID   pgtype.UUID
	Quantidade       int32
	PrecoCusto       pgtype.Numeric
	CriadoEm         pgtype.Timestamp
}

type FolhaIten struct {
	ID               pgtype.UUID
	FolhaPagamentoID pgtype.UUID
	ColaboradorID    pgtype.UUID
	SalarioBase      pgtype.Numeric
	HorasExtras      pgtype.Numeric
	ValorHorasExtras pgtype.Numeric
	DescontoInss     pgtype.Numeric
	DescontoIrrf     pgtype.Numeric
	OutrosDescontos  pgtype.Numeric
	LiquidoAReceber  pgtype.Numeric
	CriadoEm         pgtype.Timestamp
}

type FolhasPagamento struct {
	ID             pgtype.UUID
	EmpresaID      pgtype.UUID
	MesReferencia  string
	Status         string
	TotalProventos pgtype.Numeric
	TotalDescontos pgtype.Numeric
	TotalLiquido   pgtype.Numeric
	CriadoEm       pgtype.Timestamp
}

type LogsAuditoriaMaster struct {
	ID              pgtype.UUID
	UsuarioMasterID pgtype.UUID
	EmpresaID       pgtype.UUID
	Acao            string
	Detalhes        []byte
	CriadoEm        pgtype.Timestamp
}

type LogsAuditoriaSistema struct {
	ID             pgtype.UUID
	EmpresaID      pgtype.UUID
	UsuarioID      pgtype.UUID
	ImpersonatorID pgtype.UUID
	Acao           string
	Detalhes       pgtype.Text
	CriadoEm       pgtype.Timestamp
}

type NotasFiscai struct {
	ID          pgtype.UUID
	EmpresaID   pgtype.UUID
	Tipo        string
	ChaveAcesso string
	Numero      int32
	Serie       int32
	ValorTotal  pgtype.Numeric
	XmlContent  string
	Status      string
	CriadoEm    pgtype.Timestamp
}

type NotasFiscaisFila struct {
	ID           pgtype.UUID
	NotaFiscalID pgtype.UUID
	Status       string
	Tentativas   int32
	ErroLog      pgtype.Text
	CriadoEm     pgtype.Timestamp
	AtualizadoEm pgtype.Timestamp
}

type OrcamentosFornecedore struct {
	ID                  pgtype.UUID
	EmpresaID           pgtype.UUID
	SolicitacaoCompraID pgtype.UUID
	FornecedorNome      string
	ValorTotal          pgtype.Numeric
	PrazoEntregaDias    int32
	Escolhido           pgtype.Bool
	CriadoEm            pgtype.Timestamp
}

type OrcamentosFornecedoresIten struct {
	ID                    pgtype.UUID
	OrcamentoFornecedorID pgtype.UUID
	ProdutoGradeID        pgtype.UUID
	Quantidade            int32
	PrecoUnitario         pgtype.Numeric
	CriadoEm              pgtype.Timestamp
}

type OrdensServico struct {
	ID                 pgtype.UUID
	EmpresaID          pgtype.UUID
	ClienteNome        string
	VeiculoEquipamento pgtype.Text
	Status             string
	TotalPecas         pgtype.Numeric
	TotalMaoObra       pgtype.Numeric
	TotalGeral         pgtype.Numeric
	CriadoEm           pgtype.Timestamp
	AtualizadoEm       pgtype.Timestamp
}

type OsPeca struct {
	ID             pgtype.UUID
	OsID           pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoUnitario  pgtype.Numeric
	CriadoEm       pgtype.Timestamp
}

type OsServico struct {
	ID            pgtype.UUID
	OsID          pgtype.UUID
	Descricao     string
	PrecoUnitario pgtype.Numeric
	Quantidade    int32
	CriadoEm      pgtype.Timestamp
}

type PcoOrcamento struct {
	ID             pgtype.UUID
	EmpresaID      pgtype.UUID
	Categoria      string
	MesReferencia  string
	LimiteOrcado   pgtype.Numeric
	ValorRealizado pgtype.Numeric
	CriadoEm       pgtype.Timestamp
}

type PedidosCompra struct {
	ID                  pgtype.UUID
	EmpresaID           pgtype.UUID
	SolicitacaoCompraID pgtype.UUID
	FornecedorNome      string
	Status              string
	Total               pgtype.Numeric
	CriadoEm            pgtype.Timestamp
}

type PedidosCompraIten struct {
	ID             pgtype.UUID
	PedidoCompraID pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoCusto     pgtype.Numeric
	CriadoEm       pgtype.Timestamp
}

type PontoRegistro struct {
	ID               pgtype.UUID
	ColaboradorID    pgtype.UUID
	Tipo             string
	Horario          pgtype.Timestamp
	LocalizacaoGps   pgtype.Text
	FotoHash         pgtype.Text
	FacialSimilarity pgtype.Numeric
	CriadoEm         pgtype.Timestamp
}

type Produto struct {
	ID        pgtype.UUID
	EmpresaID pgtype.UUID
	Nome      string
	Descricao pgtype.Text
	SkuPai    string
	CriadoEm  pgtype.Timestamp
}

type ProdutosGrade struct {
	ID            pgtype.UUID
	ProdutoID     pgtype.UUID
	Sku           string
	Cor           pgtype.Text
	Tamanho       pgtype.Text
	CodigoBarras  pgtype.Text
	EstoqueAtual  int32
	EstoqueMinimo int32
	PrecoVenda    pgtype.Numeric
	PrecoCusto    pgtype.Numeric
	CriadoEm      pgtype.Timestamp
}

type SolicitacoesCompra struct {
	ID          pgtype.UUID
	EmpresaID   pgtype.UUID
	UsuarioID   pgtype.UUID
	Status      string
	Observacoes pgtype.Text
	CriadoEm    pgtype.Timestamp
}

type SolicitacoesCompraIten struct {
	ID                  pgtype.UUID
	SolicitacaoCompraID pgtype.UUID
	ProdutoGradeID      pgtype.UUID
	Quantidade          int32
	CriadoEm            pgtype.Timestamp
}

type Usuario struct {
	ID           pgtype.UUID
	EmpresaID    pgtype.UUID
	Nome         string
	Email        string
	SenhaHash    string
	Cargo        pgtype.Text
	IsMaster     pgtype.Bool
	Status       pgtype.Text
	CriadoEm     pgtype.Timestamp
	AtualizadoEm pgtype.Timestamp
}

type UsuarioPermisso struct {
	UsuarioID      pgtype.UUID
	ModuloID       string
	PodeVisualizar pgtype.Bool
	PodeCriar      pgtype.Bool
	PodeEditar     pgtype.Bool
	PodeDeletar    pgtype.Bool
}

type Venda struct {
	ID             pgtype.UUID
	EmpresaID      pgtype.UUID
	Total          pgtype.Numeric
	Status         string
	FormaPagamento string
	ChaveNfe       pgtype.Text
	OfflineUuid    pgtype.UUID
	CriadoEm       pgtype.Timestamp
}

type VendaIten struct {
	ID             pgtype.UUID
	VendaID        pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoUnitario  pgtype.Numeric
	CriadoEm       pgtype.Timestamp
}
