// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const baixarContasDoBorderop = `-- name: BaixarContasDoBorderop :many
UPDATE contas_pagar
SET status = 'PAGO', data_pagamento = $2
WHERE borderop_id = $1
RETURNING id, empresa_id, borderop_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em
`

type BaixarContasDoBorderopParams struct {
	BorderopID    pgtype.UUID
	DataPagamento pgtype.Timestamp
}

func (q *Queries) BaixarContasDoBorderop(ctx context.Context, arg BaixarContasDoBorderopParams) ([]ContasPagar, error) {
	rows, err := q.db.Query(ctx, baixarContasDoBorderop, arg.BorderopID, arg.DataPagamento)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContasPagar
	for rows.Next() {
		var i ContasPagar
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.BorderopID,
			&i.Descricao,
			&i.Valor,
			&i.DataVencimento,
			&i.Status,
			&i.Origem,
			&i.OrigemID,
			&i.DataPagamento,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO logs_auditoria_master (
    usuario_master_id, empresa_id, acao, detalhes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, usuario_master_id, empresa_id, acao, detalhes, criado_em
`

type CreateAuditLogParams struct {
	UsuarioMasterID pgtype.UUID
	EmpresaID       pgtype.UUID
	Acao            string
	Detalhes        []byte
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (LogsAuditoriaMaster, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UsuarioMasterID,
		arg.EmpresaID,
		arg.Acao,
		arg.Detalhes,
	)
	var i LogsAuditoriaMaster
	err := row.Scan(
		&i.ID,
		&i.UsuarioMasterID,
		&i.EmpresaID,
		&i.Acao,
		&i.Detalhes,
		&i.CriadoEm,
	)
	return i, err
}

const createBorderop = `-- name: CreateBorderop :one
INSERT INTO borderos (
    empresa_id, descricao, status
) VALUES (
    $1, $2, $3
)
RETURNING id, empresa_id, descricao, status, criado_em
`

type CreateBorderopParams struct {
	EmpresaID pgtype.UUID
	Descricao string
	Status    string
}

func (q *Queries) CreateBorderop(ctx context.Context, arg CreateBorderopParams) (Bordero, error) {
	row := q.db.QueryRow(ctx, createBorderop, arg.EmpresaID, arg.Descricao, arg.Status)
	var i Bordero
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Descricao,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const createColaborador = `-- name: CreateColaborador :one

INSERT INTO colaboradores (
    empresa_id, nome, cpf, cargo, salario, data_admissao, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, empresa_id, nome, cpf, cargo, salario, data_admissao, status, facial_biometria_template, criado_em, atualizado_em
`

type CreateColaboradorParams struct {
	EmpresaID    pgtype.UUID
	Nome         string
	Cpf          string
	Cargo        string
	Salario      pgtype.Numeric
	DataAdmissao pgtype.Date
	Status       string
}

// --- Módulo RH/DP ---
func (q *Queries) CreateColaborador(ctx context.Context, arg CreateColaboradorParams) (Colaboradore, error) {
	row := q.db.QueryRow(ctx, createColaborador,
		arg.EmpresaID,
		arg.Nome,
		arg.Cpf,
		arg.Cargo,
		arg.Salario,
		arg.DataAdmissao,
		arg.Status,
	)
	var i Colaboradore
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Cpf,
		&i.Cargo,
		&i.Salario,
		&i.DataAdmissao,
		&i.Status,
		&i.FacialBiometriaTemplate,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const createComanda = `-- name: CreateComanda :one
INSERT INTO comandas (
    empresa_id, numero_mesa_comanda, total, status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, empresa_id, numero_mesa_comanda, total, status, criado_em, atualizado_em
`

type CreateComandaParams struct {
	EmpresaID         pgtype.UUID
	NumeroMesaComanda string
	Total             pgtype.Numeric
	Status            string
}

func (q *Queries) CreateComanda(ctx context.Context, arg CreateComandaParams) (Comanda, error) {
	row := q.db.QueryRow(ctx, createComanda,
		arg.EmpresaID,
		arg.NumeroMesaComanda,
		arg.Total,
		arg.Status,
	)
	var i Comanda
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.NumeroMesaComanda,
		&i.Total,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const createComandaItem = `-- name: CreateComandaItem :one
INSERT INTO comanda_itens (
    comanda_id, produto_grade_id, quantidade, preco_unitario, status_cozinha
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, comanda_id, produto_grade_id, quantidade, preco_unitario, status_cozinha, criado_em
`

type CreateComandaItemParams struct {
	ComandaID      pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoUnitario  pgtype.Numeric
	StatusCozinha  string
}

func (q *Queries) CreateComandaItem(ctx context.Context, arg CreateComandaItemParams) (ComandaIten, error) {
	row := q.db.QueryRow(ctx, createComandaItem,
		arg.ComandaID,
		arg.ProdutoGradeID,
		arg.Quantidade,
		arg.PrecoUnitario,
		arg.StatusCozinha,
	)
	var i ComandaIten
	err := row.Scan(
		&i.ID,
		&i.ComandaID,
		&i.ProdutoGradeID,
		&i.Quantidade,
		&i.PrecoUnitario,
		&i.StatusCozinha,
		&i.CriadoEm,
	)
	return i, err
}

const createContaPagar = `-- name: CreateContaPagar :one

INSERT INTO contas_pagar (
    empresa_id, descricao, valor, data_vencimento, status, origem, origem_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, empresa_id, borderop_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em
`

type CreateContaPagarParams struct {
	EmpresaID      pgtype.UUID
	Descricao      string
	Valor          pgtype.Numeric
	DataVencimento pgtype.Date
	Status         string
	Origem         string
	OrigemID       pgtype.UUID
}

// --- Módulo Financeiro ---
func (q *Queries) CreateContaPagar(ctx context.Context, arg CreateContaPagarParams) (ContasPagar, error) {
	row := q.db.QueryRow(ctx, createContaPagar,
		arg.EmpresaID,
		arg.Descricao,
		arg.Valor,
		arg.DataVencimento,
		arg.Status,
		arg.Origem,
		arg.OrigemID,
	)
	var i ContasPagar
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.BorderopID,
		&i.Descricao,
		&i.Valor,
		&i.DataVencimento,
		&i.Status,
		&i.Origem,
		&i.OrigemID,
		&i.DataPagamento,
		&i.CriadoEm,
	)
	return i, err
}

const createContaReceber = `-- name: CreateContaReceber :one
INSERT INTO contas_receber (
    empresa_id, descricao, valor, data_vencimento, status, origem, origem_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, empresa_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em
`

type CreateContaReceberParams struct {
	EmpresaID      pgtype.UUID
	Descricao      string
	Valor          pgtype.Numeric
	DataVencimento pgtype.Date
	Status         string
	Origem         string
	OrigemID       pgtype.UUID
}

func (q *Queries) CreateContaReceber(ctx context.Context, arg CreateContaReceberParams) (ContasReceber, error) {
	row := q.db.QueryRow(ctx, createContaReceber,
		arg.EmpresaID,
		arg.Descricao,
		arg.Valor,
		arg.DataVencimento,
		arg.Status,
		arg.Origem,
		arg.OrigemID,
	)
	var i ContasReceber
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Descricao,
		&i.Valor,
		&i.DataVencimento,
		&i.Status,
		&i.Origem,
		&i.OrigemID,
		&i.DataPagamento,
		&i.CriadoEm,
	)
	return i, err
}

const createEmpresa = `-- name: CreateEmpresa :one
INSERT INTO empresas (
    razao_social, cnpj, nicho, 
    modulo_rh, modulo_kds, modulo_mesas_comandas, 
    modulo_ordem_servico, modulo_grade_produtos, modulo_self_checkout, 
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, razao_social, cnpj, nicho, modulo_rh, modulo_kds, modulo_mesas_comandas, modulo_ordem_servico, modulo_grade_produtos, modulo_self_checkout, modulo_ponto_facial, status, criado_em, atualizado_em
`

type CreateEmpresaParams struct {
	RazaoSocial         string
	Cnpj                string
	Nicho               string
	ModuloRh            pgtype.Bool
	ModuloKds           pgtype.Bool
	ModuloMesasComandas pgtype.Bool
	ModuloOrdemServico  pgtype.Bool
	ModuloGradeProdutos pgtype.Bool
	ModuloSelfCheckout  pgtype.Bool
	Status              pgtype.Text
}

func (q *Queries) CreateEmpresa(ctx context.Context, arg CreateEmpresaParams) (Empresa, error) {
	row := q.db.QueryRow(ctx, createEmpresa,
		arg.RazaoSocial,
		arg.Cnpj,
		arg.Nicho,
		arg.ModuloRh,
		arg.ModuloKds,
		arg.ModuloMesasComandas,
		arg.ModuloOrdemServico,
		arg.ModuloGradeProdutos,
		arg.ModuloSelfCheckout,
		arg.Status,
	)
	var i Empresa
	err := row.Scan(
		&i.ID,
		&i.RazaoSocial,
		&i.Cnpj,
		&i.Nicho,
		&i.ModuloRh,
		&i.ModuloKds,
		&i.ModuloMesasComandas,
		&i.ModuloOrdemServico,
		&i.ModuloGradeProdutos,
		&i.ModuloSelfCheckout,
		&i.ModuloPontoFacial,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const createEntradaEstoque = `-- name: CreateEntradaEstoque :one
INSERT INTO entradas_estoque (
    empresa_id, pedido_compra_id, chave_nfe, xml_nfe
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, empresa_id, pedido_compra_id, chave_nfe, xml_nfe, criado_em
`

type CreateEntradaEstoqueParams struct {
	EmpresaID      pgtype.UUID
	PedidoCompraID pgtype.UUID
	ChaveNfe       pgtype.Text
	XmlNfe         pgtype.Text
}

func (q *Queries) CreateEntradaEstoque(ctx context.Context, arg CreateEntradaEstoqueParams) (EntradasEstoque, error) {
	row := q.db.QueryRow(ctx, createEntradaEstoque,
		arg.EmpresaID,
		arg.PedidoCompraID,
		arg.ChaveNfe,
		arg.XmlNfe,
	)
	var i EntradasEstoque
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.PedidoCompraID,
		&i.ChaveNfe,
		&i.XmlNfe,
		&i.CriadoEm,
	)
	return i, err
}

const createEntradaEstoqueItem = `-- name: CreateEntradaEstoqueItem :one
INSERT INTO entradas_estoque_itens (
    entrada_estoque_id, produto_grade_id, quantidade, preco_custo
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, entrada_estoque_id, produto_grade_id, quantidade, preco_custo, criado_em
`

type CreateEntradaEstoqueItemParams struct {
	EntradaEstoqueID pgtype.UUID
	ProdutoGradeID   pgtype.UUID
	Quantidade       int32
	PrecoCusto       pgtype.Numeric
}

func (q *Queries) CreateEntradaEstoqueItem(ctx context.Context, arg CreateEntradaEstoqueItemParams) (EntradasEstoqueIten, error) {
	row := q.db.QueryRow(ctx, createEntradaEstoqueItem,
		arg.EntradaEstoqueID,
		arg.ProdutoGradeID,
		arg.Quantidade,
		arg.PrecoCusto,
	)
	var i EntradasEstoqueIten
	err := row.Scan(
		&i.ID,
		&i.EntradaEstoqueID,
		&i.ProdutoGradeID,
		&i.Quantidade,
		&i.PrecoCusto,
		&i.CriadoEm,
	)
	return i, err
}

const createFolhaItem = `-- name: CreateFolhaItem :one
INSERT INTO folha_itens (
    folha_pagamento_id, colaborador_id, salario_base, horas_extras, valor_horas_extras, desconto_inss, desconto_irrf, outros_descontos, liquido_a_receber
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, folha_pagamento_id, colaborador_id, salario_base, horas_extras, valor_horas_extras, desconto_inss, desconto_irrf, outros_descontos, liquido_a_receber, criado_em
`

type CreateFolhaItemParams struct {
	FolhaPagamentoID pgtype.UUID
	ColaboradorID    pgtype.UUID
	SalarioBase      pgtype.Numeric
	HorasExtras      pgtype.Numeric
	ValorHorasExtras pgtype.Numeric
	DescontoInss     pgtype.Numeric
	DescontoIrrf     pgtype.Numeric
	OutrosDescontos  pgtype.Numeric
	LiquidoAReceber  pgtype.Numeric
}

func (q *Queries) CreateFolhaItem(ctx context.Context, arg CreateFolhaItemParams) (FolhaIten, error) {
	row := q.db.QueryRow(ctx, createFolhaItem,
		arg.FolhaPagamentoID,
		arg.ColaboradorID,
		arg.SalarioBase,
		arg.HorasExtras,
		arg.ValorHorasExtras,
		arg.DescontoInss,
		arg.DescontoIrrf,
		arg.OutrosDescontos,
		arg.LiquidoAReceber,
	)
	var i FolhaIten
	err := row.Scan(
		&i.ID,
		&i.FolhaPagamentoID,
		&i.ColaboradorID,
		&i.SalarioBase,
		&i.HorasExtras,
		&i.ValorHorasExtras,
		&i.DescontoInss,
		&i.DescontoIrrf,
		&i.OutrosDescontos,
		&i.LiquidoAReceber,
		&i.CriadoEm,
	)
	return i, err
}

const createFolhaPagamento = `-- name: CreateFolhaPagamento :one
INSERT INTO folhas_pagamento (
    empresa_id, mes_referencia, status, total_proventos, total_descontos, total_liquido
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, empresa_id, mes_referencia, status, total_proventos, total_descontos, total_liquido, criado_em
`

type CreateFolhaPagamentoParams struct {
	EmpresaID      pgtype.UUID
	MesReferencia  string
	Status         string
	TotalProventos pgtype.Numeric
	TotalDescontos pgtype.Numeric
	TotalLiquido   pgtype.Numeric
}

func (q *Queries) CreateFolhaPagamento(ctx context.Context, arg CreateFolhaPagamentoParams) (FolhasPagamento, error) {
	row := q.db.QueryRow(ctx, createFolhaPagamento,
		arg.EmpresaID,
		arg.MesReferencia,
		arg.Status,
		arg.TotalProventos,
		arg.TotalDescontos,
		arg.TotalLiquido,
	)
	var i FolhasPagamento
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.MesReferencia,
		&i.Status,
		&i.TotalProventos,
		&i.TotalDescontos,
		&i.TotalLiquido,
		&i.CriadoEm,
	)
	return i, err
}

const createNotaFiscal = `-- name: CreateNotaFiscal :one

INSERT INTO notas_fiscais (
    empresa_id, tipo, chave_acesso, numero, serie, valor_total, xml_content, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, empresa_id, tipo, chave_acesso, numero, serie, valor_total, xml_content, status, criado_em
`

type CreateNotaFiscalParams struct {
	EmpresaID   pgtype.UUID
	Tipo        string
	ChaveAcesso string
	Numero      int32
	Serie       int32
	ValorTotal  pgtype.Numeric
	XmlContent  string
	Status      string
}

// --- Módulo Fiscal ---
func (q *Queries) CreateNotaFiscal(ctx context.Context, arg CreateNotaFiscalParams) (NotasFiscai, error) {
	row := q.db.QueryRow(ctx, createNotaFiscal,
		arg.EmpresaID,
		arg.Tipo,
		arg.ChaveAcesso,
		arg.Numero,
		arg.Serie,
		arg.ValorTotal,
		arg.XmlContent,
		arg.Status,
	)
	var i NotasFiscai
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Tipo,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ValorTotal,
		&i.XmlContent,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const createOSPeca = `-- name: CreateOSPeca :one
INSERT INTO os_pecas (
    os_id, produto_grade_id, quantidade, preco_unitario
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, os_id, produto_grade_id, quantidade, preco_unitario, criado_em
`

type CreateOSPecaParams struct {
	OsID           pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoUnitario  pgtype.Numeric
}

func (q *Queries) CreateOSPeca(ctx context.Context, arg CreateOSPecaParams) (OsPeca, error) {
	row := q.db.QueryRow(ctx, createOSPeca,
		arg.OsID,
		arg.ProdutoGradeID,
		arg.Quantidade,
		arg.PrecoUnitario,
	)
	var i OsPeca
	err := row.Scan(
		&i.ID,
		&i.OsID,
		&i.ProdutoGradeID,
		&i.Quantidade,
		&i.PrecoUnitario,
		&i.CriadoEm,
	)
	return i, err
}

const createOSServico = `-- name: CreateOSServico :one
INSERT INTO os_servicos (
    os_id, descricao, preco_unitario, quantidade
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, os_id, descricao, preco_unitario, quantidade, criado_em
`

type CreateOSServicoParams struct {
	OsID          pgtype.UUID
	Descricao     string
	PrecoUnitario pgtype.Numeric
	Quantidade    int32
}

func (q *Queries) CreateOSServico(ctx context.Context, arg CreateOSServicoParams) (OsServico, error) {
	row := q.db.QueryRow(ctx, createOSServico,
		arg.OsID,
		arg.Descricao,
		arg.PrecoUnitario,
		arg.Quantidade,
	)
	var i OsServico
	err := row.Scan(
		&i.ID,
		&i.OsID,
		&i.Descricao,
		&i.PrecoUnitario,
		&i.Quantidade,
		&i.CriadoEm,
	)
	return i, err
}

const createOrcamentoFornecedor = `-- name: CreateOrcamentoFornecedor :one
INSERT INTO orcamentos_fornecedores (
    empresa_id, solicitacao_compra_id, fornecedor_nome, valor_total, prazo_entrega_dias, escolhido
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, empresa_id, solicitacao_compra_id, fornecedor_nome, valor_total, prazo_entrega_dias, escolhido, criado_em
`

type CreateOrcamentoFornecedorParams struct {
	EmpresaID           pgtype.UUID
	SolicitacaoCompraID pgtype.UUID
	FornecedorNome      string
	ValorTotal          pgtype.Numeric
	PrazoEntregaDias    int32
	Escolhido           pgtype.Bool
}

func (q *Queries) CreateOrcamentoFornecedor(ctx context.Context, arg CreateOrcamentoFornecedorParams) (OrcamentosFornecedore, error) {
	row := q.db.QueryRow(ctx, createOrcamentoFornecedor,
		arg.EmpresaID,
		arg.SolicitacaoCompraID,
		arg.FornecedorNome,
		arg.ValorTotal,
		arg.PrazoEntregaDias,
		arg.Escolhido,
	)
	var i OrcamentosFornecedore
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.SolicitacaoCompraID,
		&i.FornecedorNome,
		&i.ValorTotal,
		&i.PrazoEntregaDias,
		&i.Escolhido,
		&i.CriadoEm,
	)
	return i, err
}

const createOrcamentoFornecedorItem = `-- name: CreateOrcamentoFornecedorItem :one
INSERT INTO orcamentos_fornecedores_itens (
    orcamento_fornecedor_id, produto_grade_id, quantidade, preco_unitario
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, orcamento_fornecedor_id, produto_grade_id, quantidade, preco_unitario, criado_em
`

type CreateOrcamentoFornecedorItemParams struct {
	OrcamentoFornecedorID pgtype.UUID
	ProdutoGradeID        pgtype.UUID
	Quantidade            int32
	PrecoUnitario         pgtype.Numeric
}

func (q *Queries) CreateOrcamentoFornecedorItem(ctx context.Context, arg CreateOrcamentoFornecedorItemParams) (OrcamentosFornecedoresIten, error) {
	row := q.db.QueryRow(ctx, createOrcamentoFornecedorItem,
		arg.OrcamentoFornecedorID,
		arg.ProdutoGradeID,
		arg.Quantidade,
		arg.PrecoUnitario,
	)
	var i OrcamentosFornecedoresIten
	err := row.Scan(
		&i.ID,
		&i.OrcamentoFornecedorID,
		&i.ProdutoGradeID,
		&i.Quantidade,
		&i.PrecoUnitario,
		&i.CriadoEm,
	)
	return i, err
}

const createOrdemServico = `-- name: CreateOrdemServico :one
INSERT INTO ordens_servico (
    empresa_id, cliente_nome, veiculo_equipamento, status, total_pecas, total_mao_obra, total_geral
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, empresa_id, cliente_nome, veiculo_equipamento, status, total_pecas, total_mao_obra, total_geral, criado_em, atualizado_em
`

type CreateOrdemServicoParams struct {
	EmpresaID          pgtype.UUID
	ClienteNome        string
	VeiculoEquipamento pgtype.Text
	Status             string
	TotalPecas         pgtype.Numeric
	TotalMaoObra       pgtype.Numeric
	TotalGeral         pgtype.Numeric
}

func (q *Queries) CreateOrdemServico(ctx context.Context, arg CreateOrdemServicoParams) (OrdensServico, error) {
	row := q.db.QueryRow(ctx, createOrdemServico,
		arg.EmpresaID,
		arg.ClienteNome,
		arg.VeiculoEquipamento,
		arg.Status,
		arg.TotalPecas,
		arg.TotalMaoObra,
		arg.TotalGeral,
	)
	var i OrdensServico
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ClienteNome,
		&i.VeiculoEquipamento,
		&i.Status,
		&i.TotalPecas,
		&i.TotalMaoObra,
		&i.TotalGeral,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const createPcoOrcamento = `-- name: CreatePcoOrcamento :one
INSERT INTO pco_orcamentos (
    empresa_id, categoria, mes_referencia, limite_orcado, valor_realizado
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (empresa_id, categoria, mes_referencia) DO UPDATE
SET limite_orcado = EXCLUDED.limite_orcado
RETURNING id, empresa_id, categoria, mes_referencia, limite_orcado, valor_realizado, criado_em
`

type CreatePcoOrcamentoParams struct {
	EmpresaID      pgtype.UUID
	Categoria      string
	MesReferencia  string
	LimiteOrcado   pgtype.Numeric
	ValorRealizado pgtype.Numeric
}

func (q *Queries) CreatePcoOrcamento(ctx context.Context, arg CreatePcoOrcamentoParams) (PcoOrcamento, error) {
	row := q.db.QueryRow(ctx, createPcoOrcamento,
		arg.EmpresaID,
		arg.Categoria,
		arg.MesReferencia,
		arg.LimiteOrcado,
		arg.ValorRealizado,
	)
	var i PcoOrcamento
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Categoria,
		&i.MesReferencia,
		&i.LimiteOrcado,
		&i.ValorRealizado,
		&i.CriadoEm,
	)
	return i, err
}

const createPedidoCompra = `-- name: CreatePedidoCompra :one
INSERT INTO pedidos_compra (
    empresa_id, solicitacao_compra_id, fornecedor_nome, status, total
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, empresa_id, solicitacao_compra_id, fornecedor_nome, status, total, criado_em
`

type CreatePedidoCompraParams struct {
	EmpresaID           pgtype.UUID
	SolicitacaoCompraID pgtype.UUID
	FornecedorNome      string
	Status              string
	Total               pgtype.Numeric
}

func (q *Queries) CreatePedidoCompra(ctx context.Context, arg CreatePedidoCompraParams) (PedidosCompra, error) {
	row := q.db.QueryRow(ctx, createPedidoCompra,
		arg.EmpresaID,
		arg.SolicitacaoCompraID,
		arg.FornecedorNome,
		arg.Status,
		arg.Total,
	)
	var i PedidosCompra
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.SolicitacaoCompraID,
		&i.FornecedorNome,
		&i.Status,
		&i.Total,
		&i.CriadoEm,
	)
	return i, err
}

const createPedidoCompraItem = `-- name: CreatePedidoCompraItem :one
INSERT INTO pedidos_compra_itens (
    pedido_compra_id, produto_grade_id, quantidade, preco_custo
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, pedido_compra_id, produto_grade_id, quantidade, preco_custo, criado_em
`

type CreatePedidoCompraItemParams struct {
	PedidoCompraID pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoCusto     pgtype.Numeric
}

func (q *Queries) CreatePedidoCompraItem(ctx context.Context, arg CreatePedidoCompraItemParams) (PedidosCompraIten, error) {
	row := q.db.QueryRow(ctx, createPedidoCompraItem,
		arg.PedidoCompraID,
		arg.ProdutoGradeID,
		arg.Quantidade,
		arg.PrecoCusto,
	)
	var i PedidosCompraIten
	err := row.Scan(
		&i.ID,
		&i.PedidoCompraID,
		&i.ProdutoGradeID,
		&i.Quantidade,
		&i.PrecoCusto,
		&i.CriadoEm,
	)
	return i, err
}

const createPontoFacial = `-- name: CreatePontoFacial :one
INSERT INTO ponto_registros (
    colaborador_id, tipo, horario, localizacao_gps, foto_hash, facial_similarity
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, colaborador_id, tipo, horario, localizacao_gps, foto_hash, facial_similarity, criado_em
`

type CreatePontoFacialParams struct {
	ColaboradorID    pgtype.UUID
	Tipo             string
	Horario          pgtype.Timestamp
	LocalizacaoGps   pgtype.Text
	FotoHash         pgtype.Text
	FacialSimilarity pgtype.Numeric
}

func (q *Queries) CreatePontoFacial(ctx context.Context, arg CreatePontoFacialParams) (PontoRegistro, error) {
	row := q.db.QueryRow(ctx, createPontoFacial,
		arg.ColaboradorID,
		arg.Tipo,
		arg.Horario,
		arg.LocalizacaoGps,
		arg.FotoHash,
		arg.FacialSimilarity,
	)
	var i PontoRegistro
	err := row.Scan(
		&i.ID,
		&i.ColaboradorID,
		&i.Tipo,
		&i.Horario,
		&i.LocalizacaoGps,
		&i.FotoHash,
		&i.FacialSimilarity,
		&i.CriadoEm,
	)
	return i, err
}

const createPontoRegistro = `-- name: CreatePontoRegistro :one
INSERT INTO ponto_registros (
    colaborador_id, tipo, horario
) VALUES (
    $1, $2, $3
)
RETURNING id, colaborador_id, tipo, horario, localizacao_gps, foto_hash, facial_similarity, criado_em
`

type CreatePontoRegistroParams struct {
	ColaboradorID pgtype.UUID
	Tipo          string
	Horario       pgtype.Timestamp
}

func (q *Queries) CreatePontoRegistro(ctx context.Context, arg CreatePontoRegistroParams) (PontoRegistro, error) {
	row := q.db.QueryRow(ctx, createPontoRegistro, arg.ColaboradorID, arg.Tipo, arg.Horario)
	var i PontoRegistro
	err := row.Scan(
		&i.ID,
		&i.ColaboradorID,
		&i.Tipo,
		&i.Horario,
		&i.LocalizacaoGps,
		&i.FotoHash,
		&i.FacialSimilarity,
		&i.CriadoEm,
	)
	return i, err
}

const createProduto = `-- name: CreateProduto :one

INSERT INTO produtos (
    empresa_id, nome, descricao, sku_pai
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, empresa_id, nome, descricao, sku_pai, criado_em
`

type CreateProdutoParams struct {
	EmpresaID pgtype.UUID
	Nome      string
	Descricao pgtype.Text
	SkuPai    string
}

// --- Módulo Estoque & Compras ---
func (q *Queries) CreateProduto(ctx context.Context, arg CreateProdutoParams) (Produto, error) {
	row := q.db.QueryRow(ctx, createProduto,
		arg.EmpresaID,
		arg.Nome,
		arg.Descricao,
		arg.SkuPai,
	)
	var i Produto
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Descricao,
		&i.SkuPai,
		&i.CriadoEm,
	)
	return i, err
}

const createProdutoGrade = `-- name: CreateProdutoGrade :one
INSERT INTO produtos_grade (
    produto_id, sku, cor, tamanho, codigo_barras, estoque_atual, estoque_minimo, preco_venda, preco_custo
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, produto_id, sku, cor, tamanho, codigo_barras, estoque_atual, estoque_minimo, preco_venda, preco_custo, criado_em
`

type CreateProdutoGradeParams struct {
	ProdutoID     pgtype.UUID
	Sku           string
	Cor           pgtype.Text
	Tamanho       pgtype.Text
	CodigoBarras  pgtype.Text
	EstoqueAtual  int32
	EstoqueMinimo int32
	PrecoVenda    pgtype.Numeric
	PrecoCusto    pgtype.Numeric
}

func (q *Queries) CreateProdutoGrade(ctx context.Context, arg CreateProdutoGradeParams) (ProdutosGrade, error) {
	row := q.db.QueryRow(ctx, createProdutoGrade,
		arg.ProdutoID,
		arg.Sku,
		arg.Cor,
		arg.Tamanho,
		arg.CodigoBarras,
		arg.EstoqueAtual,
		arg.EstoqueMinimo,
		arg.PrecoVenda,
		arg.PrecoCusto,
	)
	var i ProdutosGrade
	err := row.Scan(
		&i.ID,
		&i.ProdutoID,
		&i.Sku,
		&i.Cor,
		&i.Tamanho,
		&i.CodigoBarras,
		&i.EstoqueAtual,
		&i.EstoqueMinimo,
		&i.PrecoVenda,
		&i.PrecoCusto,
		&i.CriadoEm,
	)
	return i, err
}

const createSolicitacaoCompra = `-- name: CreateSolicitacaoCompra :one
INSERT INTO solicitacoes_compra (
    empresa_id, usuario_id, status, observacoes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, empresa_id, usuario_id, status, observacoes, criado_em
`

type CreateSolicitacaoCompraParams struct {
	EmpresaID   pgtype.UUID
	UsuarioID   pgtype.UUID
	Status      string
	Observacoes pgtype.Text
}

func (q *Queries) CreateSolicitacaoCompra(ctx context.Context, arg CreateSolicitacaoCompraParams) (SolicitacoesCompra, error) {
	row := q.db.QueryRow(ctx, createSolicitacaoCompra,
		arg.EmpresaID,
		arg.UsuarioID,
		arg.Status,
		arg.Observacoes,
	)
	var i SolicitacoesCompra
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.UsuarioID,
		&i.Status,
		&i.Observacoes,
		&i.CriadoEm,
	)
	return i, err
}

const createSolicitacaoCompraItem = `-- name: CreateSolicitacaoCompraItem :one
INSERT INTO solicitacoes_compra_itens (
    solicitacao_compra_id, produto_grade_id, quantidade
) VALUES (
    $1, $2, $3
)
RETURNING id, solicitacao_compra_id, produto_grade_id, quantidade, criado_em
`

type CreateSolicitacaoCompraItemParams struct {
	SolicitacaoCompraID pgtype.UUID
	ProdutoGradeID      pgtype.UUID
	Quantidade          int32
}

func (q *Queries) CreateSolicitacaoCompraItem(ctx context.Context, arg CreateSolicitacaoCompraItemParams) (SolicitacoesCompraIten, error) {
	row := q.db.QueryRow(ctx, createSolicitacaoCompraItem, arg.SolicitacaoCompraID, arg.ProdutoGradeID, arg.Quantidade)
	var i SolicitacoesCompraIten
	err := row.Scan(
		&i.ID,
		&i.SolicitacaoCompraID,
		&i.ProdutoGradeID,
		&i.Quantidade,
		&i.CriadoEm,
	)
	return i, err
}

const createSystemAuditLog = `-- name: CreateSystemAuditLog :one
INSERT INTO logs_auditoria_sistema (
    empresa_id, usuario_id, impersonator_id, acao, detalhes
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, empresa_id, usuario_id, impersonator_id, acao, detalhes, criado_em
`

type CreateSystemAuditLogParams struct {
	EmpresaID      pgtype.UUID
	UsuarioID      pgtype.UUID
	ImpersonatorID pgtype.UUID
	Acao           string
	Detalhes       pgtype.Text
}

func (q *Queries) CreateSystemAuditLog(ctx context.Context, arg CreateSystemAuditLogParams) (LogsAuditoriaSistema, error) {
	row := q.db.QueryRow(ctx, createSystemAuditLog,
		arg.EmpresaID,
		arg.UsuarioID,
		arg.ImpersonatorID,
		arg.Acao,
		arg.Detalhes,
	)
	var i LogsAuditoriaSistema
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.UsuarioID,
		&i.ImpersonatorID,
		&i.Acao,
		&i.Detalhes,
		&i.CriadoEm,
	)
	return i, err
}

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuarios (
    empresa_id, nome, email, senha_hash, cargo, is_master, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, empresa_id, nome, email, senha_hash, cargo, is_master, status, criado_em, atualizado_em
`

type CreateUsuarioParams struct {
	EmpresaID pgtype.UUID
	Nome      string
	Email     string
	SenhaHash string
	Cargo     pgtype.Text
	IsMaster  pgtype.Bool
	Status    pgtype.Text
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, createUsuario,
		arg.EmpresaID,
		arg.Nome,
		arg.Email,
		arg.SenhaHash,
		arg.Cargo,
		arg.IsMaster,
		arg.Status,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Cargo,
		&i.IsMaster,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const createVenda = `-- name: CreateVenda :one
INSERT INTO vendas (
    empresa_id, total, status, forma_pagamento, chave_nfe, offline_uuid
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, empresa_id, total, status, forma_pagamento, chave_nfe, offline_uuid, criado_em
`

type CreateVendaParams struct {
	EmpresaID      pgtype.UUID
	Total          pgtype.Numeric
	Status         string
	FormaPagamento string
	ChaveNfe       pgtype.Text
	OfflineUuid    pgtype.UUID
}

func (q *Queries) CreateVenda(ctx context.Context, arg CreateVendaParams) (Venda, error) {
	row := q.db.QueryRow(ctx, createVenda,
		arg.EmpresaID,
		arg.Total,
		arg.Status,
		arg.FormaPagamento,
		arg.ChaveNfe,
		arg.OfflineUuid,
	)
	var i Venda
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Total,
		&i.Status,
		&i.FormaPagamento,
		&i.ChaveNfe,
		&i.OfflineUuid,
		&i.CriadoEm,
	)
	return i, err
}

const createVendaItem = `-- name: CreateVendaItem :one
INSERT INTO venda_itens (
    venda_id, produto_grade_id, quantidade, preco_unitario
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, venda_id, produto_grade_id, quantidade, preco_unitario, criado_em
`

type CreateVendaItemParams struct {
	VendaID        pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoUnitario  pgtype.Numeric
}

func (q *Queries) CreateVendaItem(ctx context.Context, arg CreateVendaItemParams) (VendaIten, error) {
	row := q.db.QueryRow(ctx, createVendaItem,
		arg.VendaID,
		arg.ProdutoGradeID,
		arg.Quantidade,
		arg.PrecoUnitario,
	)
	var i VendaIten
	err := row.Scan(
		&i.ID,
		&i.VendaID,
		&i.ProdutoGradeID,
		&i.Quantidade,
		&i.PrecoUnitario,
		&i.CriadoEm,
	)
	return i, err
}

const decrementEstoqueGrade = `-- name: DecrementEstoqueGrade :one
UPDATE produtos_grade
SET estoque_atual = estoque_atual - $2
WHERE id = $1
RETURNING id, produto_id, sku, cor, tamanho, codigo_barras, estoque_atual, estoque_minimo, preco_venda, preco_custo, criado_em
`

type DecrementEstoqueGradeParams struct {
	ID           pgtype.UUID
	EstoqueAtual int32
}

func (q *Queries) DecrementEstoqueGrade(ctx context.Context, arg DecrementEstoqueGradeParams) (ProdutosGrade, error) {
	row := q.db.QueryRow(ctx, decrementEstoqueGrade, arg.ID, arg.EstoqueAtual)
	var i ProdutosGrade
	err := row.Scan(
		&i.ID,
		&i.ProdutoID,
		&i.Sku,
		&i.Cor,
		&i.Tamanho,
		&i.CodigoBarras,
		&i.EstoqueAtual,
		&i.EstoqueMinimo,
		&i.PrecoVenda,
		&i.PrecoCusto,
		&i.CriadoEm,
	)
	return i, err
}

const enfileirarNotaFiscal = `-- name: EnfileirarNotaFiscal :one
INSERT INTO notas_fiscais_fila (
    nota_fiscal_id, status, tentativas
) VALUES (
    $1, $2, $3
)
RETURNING id, nota_fiscal_id, status, tentativas, erro_log, criado_em, atualizado_em
`

type EnfileirarNotaFiscalParams struct {
	NotaFiscalID pgtype.UUID
	Status       string
	Tentativas   int32
}

func (q *Queries) EnfileirarNotaFiscal(ctx context.Context, arg EnfileirarNotaFiscalParams) (NotasFiscaisFila, error) {
	row := q.db.QueryRow(ctx, enfileirarNotaFiscal, arg.NotaFiscalID, arg.Status, arg.Tentativas)
	var i NotasFiscaisFila
	err := row.Scan(
		&i.ID,
		&i.NotaFiscalID,
		&i.Status,
		&i.Tentativas,
		&i.ErroLog,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getBankConfigByBanco = `-- name: GetBankConfigByBanco :one
SELECT id, empresa_id, banco_nome, client_id, client_secret, certificado_digital, token_atual, status, criado_em FROM configuracoes_banco WHERE empresa_id = $1 AND banco_nome = $2 LIMIT 1
`

type GetBankConfigByBancoParams struct {
	EmpresaID pgtype.UUID
	BancoNome string
}

func (q *Queries) GetBankConfigByBanco(ctx context.Context, arg GetBankConfigByBancoParams) (ConfiguracoesBanco, error) {
	row := q.db.QueryRow(ctx, getBankConfigByBanco, arg.EmpresaID, arg.BancoNome)
	var i ConfiguracoesBanco
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.BancoNome,
		&i.ClientID,
		&i.ClientSecret,
		&i.CertificadoDigital,
		&i.TokenAtual,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const getBankConfigs = `-- name: GetBankConfigs :many
SELECT id, empresa_id, banco_nome, client_id, client_secret, certificado_digital, token_atual, status, criado_em FROM configuracoes_banco WHERE empresa_id = $1
`

func (q *Queries) GetBankConfigs(ctx context.Context, empresaID pgtype.UUID) ([]ConfiguracoesBanco, error) {
	rows, err := q.db.Query(ctx, getBankConfigs, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfiguracoesBanco
	for rows.Next() {
		var i ConfiguracoesBanco
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.BancoNome,
			&i.ClientID,
			&i.ClientSecret,
			&i.CertificadoDigital,
			&i.TokenAtual,
			&i.Status,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBorderop = `-- name: GetBorderop :one
SELECT id, empresa_id, descricao, status, criado_em FROM borderos WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBorderop(ctx context.Context, id pgtype.UUID) (Bordero, error) {
	row := q.db.QueryRow(ctx, getBorderop, id)
	var i Bordero
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Descricao,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const getColaborador = `-- name: GetColaborador :one
SELECT id, empresa_id, nome, cpf, cargo, salario, data_admissao, status, facial_biometria_template, criado_em, atualizado_em FROM colaboradores WHERE id = $1 LIMIT 1
`

func (q *Queries) GetColaborador(ctx context.Context, id pgtype.UUID) (Colaboradore, error) {
	row := q.db.QueryRow(ctx, getColaborador, id)
	var i Colaboradore
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Cpf,
		&i.Cargo,
		&i.Salario,
		&i.DataAdmissao,
		&i.Status,
		&i.FacialBiometriaTemplate,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getComanda = `-- name: GetComanda :one
SELECT id, empresa_id, numero_mesa_comanda, total, status, criado_em, atualizado_em FROM comandas WHERE id = $1 LIMIT 1
`

func (q *Queries) GetComanda(ctx context.Context, id pgtype.UUID) (Comanda, error) {
	row := q.db.QueryRow(ctx, getComanda, id)
	var i Comanda
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.NumeroMesaComanda,
		&i.Total,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getComandaByNumero = `-- name: GetComandaByNumero :one
SELECT id, empresa_id, numero_mesa_comanda, total, status, criado_em, atualizado_em FROM comandas WHERE empresa_id = $1 AND numero_mesa_comanda = $2 AND status = 'ABERTA' LIMIT 1
`

type GetComandaByNumeroParams struct {
	EmpresaID         pgtype.UUID
	NumeroMesaComanda string
}

func (q *Queries) GetComandaByNumero(ctx context.Context, arg GetComandaByNumeroParams) (Comanda, error) {
	row := q.db.QueryRow(ctx, getComandaByNumero, arg.EmpresaID, arg.NumeroMesaComanda)
	var i Comanda
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.NumeroMesaComanda,
		&i.Total,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getComandaItens = `-- name: GetComandaItens :many
SELECT ci.id, ci.comanda_id, ci.produto_grade_id, ci.quantidade, ci.preco_unitario, ci.status_cozinha, ci.criado_em, pg.sku, p.nome as produto_nome FROM comanda_itens ci
JOIN produtos_grade pg ON ci.produto_grade_id = pg.id
JOIN produtos p ON pg.produto_id = p.id
WHERE ci.comanda_id = $1
`

type GetComandaItensRow struct {
	ID             pgtype.UUID
	ComandaID      pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoUnitario  pgtype.Numeric
	StatusCozinha  string
	CriadoEm       pgtype.Timestamp
	Sku            string
	ProdutoNome    string
}

func (q *Queries) GetComandaItens(ctx context.Context, comandaID pgtype.UUID) ([]GetComandaItensRow, error) {
	rows, err := q.db.Query(ctx, getComandaItens, comandaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComandaItensRow
	for rows.Next() {
		var i GetComandaItensRow
		if err := rows.Scan(
			&i.ID,
			&i.ComandaID,
			&i.ProdutoGradeID,
			&i.Quantidade,
			&i.PrecoUnitario,
			&i.StatusCozinha,
			&i.CriadoEm,
			&i.Sku,
			&i.ProdutoNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmpresa = `-- name: GetEmpresa :one
SELECT id, razao_social, cnpj, nicho, modulo_rh, modulo_kds, modulo_mesas_comandas, modulo_ordem_servico, modulo_grade_produtos, modulo_self_checkout, modulo_ponto_facial, status, criado_em, atualizado_em FROM empresas WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmpresa(ctx context.Context, id pgtype.UUID) (Empresa, error) {
	row := q.db.QueryRow(ctx, getEmpresa, id)
	var i Empresa
	err := row.Scan(
		&i.ID,
		&i.RazaoSocial,
		&i.Cnpj,
		&i.Nicho,
		&i.ModuloRh,
		&i.ModuloKds,
		&i.ModuloMesasComandas,
		&i.ModuloOrdemServico,
		&i.ModuloGradeProdutos,
		&i.ModuloSelfCheckout,
		&i.ModuloPontoFacial,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getEmpresaByCNPJ = `-- name: GetEmpresaByCNPJ :one
SELECT id, razao_social, cnpj, nicho, modulo_rh, modulo_kds, modulo_mesas_comandas, modulo_ordem_servico, modulo_grade_produtos, modulo_self_checkout, modulo_ponto_facial, status, criado_em, atualizado_em FROM empresas WHERE cnpj = $1 LIMIT 1
`

func (q *Queries) GetEmpresaByCNPJ(ctx context.Context, cnpj string) (Empresa, error) {
	row := q.db.QueryRow(ctx, getEmpresaByCNPJ, cnpj)
	var i Empresa
	err := row.Scan(
		&i.ID,
		&i.RazaoSocial,
		&i.Cnpj,
		&i.Nicho,
		&i.ModuloRh,
		&i.ModuloKds,
		&i.ModuloMesasComandas,
		&i.ModuloOrdemServico,
		&i.ModuloGradeProdutos,
		&i.ModuloSelfCheckout,
		&i.ModuloPontoFacial,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getFolhaItens = `-- name: GetFolhaItens :many
SELECT id, folha_pagamento_id, colaborador_id, salario_base, horas_extras, valor_horas_extras, desconto_inss, desconto_irrf, outros_descontos, liquido_a_receber, criado_em FROM folha_itens WHERE folha_pagamento_id = $1
`

func (q *Queries) GetFolhaItens(ctx context.Context, folhaPagamentoID pgtype.UUID) ([]FolhaIten, error) {
	rows, err := q.db.Query(ctx, getFolhaItens, folhaPagamentoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolhaIten
	for rows.Next() {
		var i FolhaIten
		if err := rows.Scan(
			&i.ID,
			&i.FolhaPagamentoID,
			&i.ColaboradorID,
			&i.SalarioBase,
			&i.HorasExtras,
			&i.ValorHorasExtras,
			&i.DescontoInss,
			&i.DescontoIrrf,
			&i.OutrosDescontos,
			&i.LiquidoAReceber,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolhaPagamento = `-- name: GetFolhaPagamento :one
SELECT id, empresa_id, mes_referencia, status, total_proventos, total_descontos, total_liquido, criado_em FROM folhas_pagamento WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFolhaPagamento(ctx context.Context, id pgtype.UUID) (FolhasPagamento, error) {
	row := q.db.QueryRow(ctx, getFolhaPagamento, id)
	var i FolhasPagamento
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.MesReferencia,
		&i.Status,
		&i.TotalProventos,
		&i.TotalDescontos,
		&i.TotalLiquido,
		&i.CriadoEm,
	)
	return i, err
}

const getFolhaPagamentoByMes = `-- name: GetFolhaPagamentoByMes :one
SELECT id, empresa_id, mes_referencia, status, total_proventos, total_descontos, total_liquido, criado_em FROM folhas_pagamento WHERE empresa_id = $1 AND mes_referencia = $2 LIMIT 1
`

type GetFolhaPagamentoByMesParams struct {
	EmpresaID     pgtype.UUID
	MesReferencia string
}

func (q *Queries) GetFolhaPagamentoByMes(ctx context.Context, arg GetFolhaPagamentoByMesParams) (FolhasPagamento, error) {
	row := q.db.QueryRow(ctx, getFolhaPagamentoByMes, arg.EmpresaID, arg.MesReferencia)
	var i FolhasPagamento
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.MesReferencia,
		&i.Status,
		&i.TotalProventos,
		&i.TotalDescontos,
		&i.TotalLiquido,
		&i.CriadoEm,
	)
	return i, err
}

const getMaxNotaFiscalNumero = `-- name: GetMaxNotaFiscalNumero :one
SELECT COALESCE(MAX(numero), 0)::int as max_numero
FROM notas_fiscais
WHERE empresa_id = $1 AND tipo = $2
`

type GetMaxNotaFiscalNumeroParams struct {
	EmpresaID pgtype.UUID
	Tipo      string
}

func (q *Queries) GetMaxNotaFiscalNumero(ctx context.Context, arg GetMaxNotaFiscalNumeroParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxNotaFiscalNumero, arg.EmpresaID, arg.Tipo)
	var max_numero int32
	err := row.Scan(&max_numero)
	return max_numero, err
}

const getNotaFiscal = `-- name: GetNotaFiscal :one
SELECT id, empresa_id, tipo, chave_acesso, numero, serie, valor_total, xml_content, status, criado_em FROM notas_fiscais WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotaFiscal(ctx context.Context, id pgtype.UUID) (NotasFiscai, error) {
	row := q.db.QueryRow(ctx, getNotaFiscal, id)
	var i NotasFiscai
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Tipo,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ValorTotal,
		&i.XmlContent,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const getNotaFiscalByChave = `-- name: GetNotaFiscalByChave :one
SELECT id, empresa_id, tipo, chave_acesso, numero, serie, valor_total, xml_content, status, criado_em FROM notas_fiscais WHERE chave_acesso = $1 LIMIT 1
`

func (q *Queries) GetNotaFiscalByChave(ctx context.Context, chaveAcesso string) (NotasFiscai, error) {
	row := q.db.QueryRow(ctx, getNotaFiscalByChave, chaveAcesso)
	var i NotasFiscai
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Tipo,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ValorTotal,
		&i.XmlContent,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const getOSPecas = `-- name: GetOSPecas :many
SELECT op.id, op.os_id, op.produto_grade_id, op.quantidade, op.preco_unitario, op.criado_em, pg.sku, p.nome as produto_nome FROM os_pecas op
JOIN produtos_grade pg ON op.produto_grade_id = pg.id
JOIN produtos p ON pg.produto_id = p.id
WHERE op.os_id = $1
`

type GetOSPecasRow struct {
	ID             pgtype.UUID
	OsID           pgtype.UUID
	ProdutoGradeID pgtype.UUID
	Quantidade     int32
	PrecoUnitario  pgtype.Numeric
	CriadoEm       pgtype.Timestamp
	Sku            string
	ProdutoNome    string
}

func (q *Queries) GetOSPecas(ctx context.Context, osID pgtype.UUID) ([]GetOSPecasRow, error) {
	rows, err := q.db.Query(ctx, getOSPecas, osID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOSPecasRow
	for rows.Next() {
		var i GetOSPecasRow
		if err := rows.Scan(
			&i.ID,
			&i.OsID,
			&i.ProdutoGradeID,
			&i.Quantidade,
			&i.PrecoUnitario,
			&i.CriadoEm,
			&i.Sku,
			&i.ProdutoNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOSServicos = `-- name: GetOSServicos :many
SELECT id, os_id, descricao, preco_unitario, quantidade, criado_em FROM os_servicos WHERE os_id = $1
`

func (q *Queries) GetOSServicos(ctx context.Context, osID pgtype.UUID) ([]OsServico, error) {
	rows, err := q.db.Query(ctx, getOSServicos, osID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OsServico
	for rows.Next() {
		var i OsServico
		if err := rows.Scan(
			&i.ID,
			&i.OsID,
			&i.Descricao,
			&i.PrecoUnitario,
			&i.Quantidade,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrcamentoFornecedor = `-- name: GetOrcamentoFornecedor :one
SELECT id, empresa_id, solicitacao_compra_id, fornecedor_nome, valor_total, prazo_entrega_dias, escolhido, criado_em FROM orcamentos_fornecedores WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrcamentoFornecedor(ctx context.Context, id pgtype.UUID) (OrcamentosFornecedore, error) {
	row := q.db.QueryRow(ctx, getOrcamentoFornecedor, id)
	var i OrcamentosFornecedore
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.SolicitacaoCompraID,
		&i.FornecedorNome,
		&i.ValorTotal,
		&i.PrazoEntregaDias,
		&i.Escolhido,
		&i.CriadoEm,
	)
	return i, err
}

const getOrcamentoFornecedorItens = `-- name: GetOrcamentoFornecedorItens :many
SELECT id, orcamento_fornecedor_id, produto_grade_id, quantidade, preco_unitario, criado_em FROM orcamentos_fornecedores_itens WHERE orcamento_fornecedor_id = $1
`

func (q *Queries) GetOrcamentoFornecedorItens(ctx context.Context, orcamentoFornecedorID pgtype.UUID) ([]OrcamentosFornecedoresIten, error) {
	rows, err := q.db.Query(ctx, getOrcamentoFornecedorItens, orcamentoFornecedorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrcamentosFornecedoresIten
	for rows.Next() {
		var i OrcamentosFornecedoresIten
		if err := rows.Scan(
			&i.ID,
			&i.OrcamentoFornecedorID,
			&i.ProdutoGradeID,
			&i.Quantidade,
			&i.PrecoUnitario,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdemServico = `-- name: GetOrdemServico :one
SELECT id, empresa_id, cliente_nome, veiculo_equipamento, status, total_pecas, total_mao_obra, total_geral, criado_em, atualizado_em FROM ordens_servico WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrdemServico(ctx context.Context, id pgtype.UUID) (OrdensServico, error) {
	row := q.db.QueryRow(ctx, getOrdemServico, id)
	var i OrdensServico
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ClienteNome,
		&i.VeiculoEquipamento,
		&i.Status,
		&i.TotalPecas,
		&i.TotalMaoObra,
		&i.TotalGeral,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getPcoOrcamento = `-- name: GetPcoOrcamento :one
SELECT id, empresa_id, categoria, mes_referencia, limite_orcado, valor_realizado, criado_em FROM pco_orcamentos 
WHERE empresa_id = $1 AND categoria = $2 AND mes_referencia = $3 
LIMIT 1
`

type GetPcoOrcamentoParams struct {
	EmpresaID     pgtype.UUID
	Categoria     string
	MesReferencia string
}

func (q *Queries) GetPcoOrcamento(ctx context.Context, arg GetPcoOrcamentoParams) (PcoOrcamento, error) {
	row := q.db.QueryRow(ctx, getPcoOrcamento, arg.EmpresaID, arg.Categoria, arg.MesReferencia)
	var i PcoOrcamento
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Categoria,
		&i.MesReferencia,
		&i.LimiteOrcado,
		&i.ValorRealizado,
		&i.CriadoEm,
	)
	return i, err
}

const getPedidoCompra = `-- name: GetPedidoCompra :one
SELECT id, empresa_id, solicitacao_compra_id, fornecedor_nome, status, total, criado_em FROM pedidos_compra WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPedidoCompra(ctx context.Context, id pgtype.UUID) (PedidosCompra, error) {
	row := q.db.QueryRow(ctx, getPedidoCompra, id)
	var i PedidosCompra
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.SolicitacaoCompraID,
		&i.FornecedorNome,
		&i.Status,
		&i.Total,
		&i.CriadoEm,
	)
	return i, err
}

const getPedidoCompraItens = `-- name: GetPedidoCompraItens :many
SELECT id, pedido_compra_id, produto_grade_id, quantidade, preco_custo, criado_em FROM pedidos_compra_itens WHERE pedido_compra_id = $1
`

func (q *Queries) GetPedidoCompraItens(ctx context.Context, pedidoCompraID pgtype.UUID) ([]PedidosCompraIten, error) {
	rows, err := q.db.Query(ctx, getPedidoCompraItens, pedidoCompraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PedidosCompraIten
	for rows.Next() {
		var i PedidosCompraIten
		if err := rows.Scan(
			&i.ID,
			&i.PedidoCompraID,
			&i.ProdutoGradeID,
			&i.Quantidade,
			&i.PrecoCusto,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlatformStats = `-- name: GetPlatformStats :one
SELECT 
    (SELECT COUNT(*) FROM empresas WHERE status = 'ATIVO')::bigint as total_tenants,
    (SELECT COUNT(*) FROM usuarios)::bigint as total_usuarios,
    (SELECT COUNT(*) FROM vendas)::bigint as total_vendas,
    (SELECT COALESCE(SUM(total), 0.00)::numeric(10,2) FROM vendas)::numeric(10,2) as faturamento_total
`

type GetPlatformStatsRow struct {
	TotalTenants     int64
	TotalUsuarios    int64
	TotalVendas      int64
	FaturamentoTotal pgtype.Numeric
}

func (q *Queries) GetPlatformStats(ctx context.Context) (GetPlatformStatsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformStats)
	var i GetPlatformStatsRow
	err := row.Scan(
		&i.TotalTenants,
		&i.TotalUsuarios,
		&i.TotalVendas,
		&i.FaturamentoTotal,
	)
	return i, err
}

const getPontoRegistros = `-- name: GetPontoRegistros :many
SELECT pr.id, pr.colaborador_id, pr.tipo, pr.horario, pr.localizacao_gps, pr.foto_hash, pr.facial_similarity, pr.criado_em FROM ponto_registros pr
JOIN colaboradores c ON pr.colaborador_id = c.id
WHERE c.empresa_id = $1 AND pr.horario >= $2 AND pr.horario <= $3
ORDER BY pr.horario ASC
`

type GetPontoRegistrosParams struct {
	EmpresaID pgtype.UUID
	Horario   pgtype.Timestamp
	Horario_2 pgtype.Timestamp
}

func (q *Queries) GetPontoRegistros(ctx context.Context, arg GetPontoRegistrosParams) ([]PontoRegistro, error) {
	rows, err := q.db.Query(ctx, getPontoRegistros, arg.EmpresaID, arg.Horario, arg.Horario_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PontoRegistro
	for rows.Next() {
		var i PontoRegistro
		if err := rows.Scan(
			&i.ID,
			&i.ColaboradorID,
			&i.Tipo,
			&i.Horario,
			&i.LocalizacaoGps,
			&i.FotoHash,
			&i.FacialSimilarity,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduto = `-- name: GetProduto :one
SELECT id, empresa_id, nome, descricao, sku_pai, criado_em FROM produtos WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduto(ctx context.Context, id pgtype.UUID) (Produto, error) {
	row := q.db.QueryRow(ctx, getProduto, id)
	var i Produto
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Descricao,
		&i.SkuPai,
		&i.CriadoEm,
	)
	return i, err
}

const getProdutoGrade = `-- name: GetProdutoGrade :one
SELECT id, produto_id, sku, cor, tamanho, codigo_barras, estoque_atual, estoque_minimo, preco_venda, preco_custo, criado_em FROM produtos_grade WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProdutoGrade(ctx context.Context, id pgtype.UUID) (ProdutosGrade, error) {
	row := q.db.QueryRow(ctx, getProdutoGrade, id)
	var i ProdutosGrade
	err := row.Scan(
		&i.ID,
		&i.ProdutoID,
		&i.Sku,
		&i.Cor,
		&i.Tamanho,
		&i.CodigoBarras,
		&i.EstoqueAtual,
		&i.EstoqueMinimo,
		&i.PrecoVenda,
		&i.PrecoCusto,
		&i.CriadoEm,
	)
	return i, err
}

const getProdutoGradeBySKU = `-- name: GetProdutoGradeBySKU :one
SELECT id, produto_id, sku, cor, tamanho, codigo_barras, estoque_atual, estoque_minimo, preco_venda, preco_custo, criado_em FROM produtos_grade WHERE sku = $1 LIMIT 1
`

func (q *Queries) GetProdutoGradeBySKU(ctx context.Context, sku string) (ProdutosGrade, error) {
	row := q.db.QueryRow(ctx, getProdutoGradeBySKU, sku)
	var i ProdutosGrade
	err := row.Scan(
		&i.ID,
		&i.ProdutoID,
		&i.Sku,
		&i.Cor,
		&i.Tamanho,
		&i.CodigoBarras,
		&i.EstoqueAtual,
		&i.EstoqueMinimo,
		&i.PrecoVenda,
		&i.PrecoCusto,
		&i.CriadoEm,
	)
	return i, err
}

const getProdutoGradeParaUpdate = `-- name: GetProdutoGradeParaUpdate :one
SELECT id, produto_id, sku, cor, tamanho, codigo_barras, estoque_atual, estoque_minimo, preco_venda, preco_custo, criado_em FROM produtos_grade WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetProdutoGradeParaUpdate(ctx context.Context, id pgtype.UUID) (ProdutosGrade, error) {
	row := q.db.QueryRow(ctx, getProdutoGradeParaUpdate, id)
	var i ProdutosGrade
	err := row.Scan(
		&i.ID,
		&i.ProdutoID,
		&i.Sku,
		&i.Cor,
		&i.Tamanho,
		&i.CodigoBarras,
		&i.EstoqueAtual,
		&i.EstoqueMinimo,
		&i.PrecoVenda,
		&i.PrecoCusto,
		&i.CriadoEm,
	)
	return i, err
}

const getSolicitacaoCompra = `-- name: GetSolicitacaoCompra :one
SELECT id, empresa_id, usuario_id, status, observacoes, criado_em FROM solicitacoes_compra WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSolicitacaoCompra(ctx context.Context, id pgtype.UUID) (SolicitacoesCompra, error) {
	row := q.db.QueryRow(ctx, getSolicitacaoCompra, id)
	var i SolicitacoesCompra
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.UsuarioID,
		&i.Status,
		&i.Observacoes,
		&i.CriadoEm,
	)
	return i, err
}

const getSolicitacaoCompraItens = `-- name: GetSolicitacaoCompraItens :many
SELECT id, solicitacao_compra_id, produto_grade_id, quantidade, criado_em FROM solicitacoes_compra_itens WHERE solicitacao_compra_id = $1
`

func (q *Queries) GetSolicitacaoCompraItens(ctx context.Context, solicitacaoCompraID pgtype.UUID) ([]SolicitacoesCompraIten, error) {
	rows, err := q.db.Query(ctx, getSolicitacaoCompraItens, solicitacaoCompraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SolicitacoesCompraIten
	for rows.Next() {
		var i SolicitacoesCompraIten
		if err := rows.Scan(
			&i.ID,
			&i.SolicitacaoCompraID,
			&i.ProdutoGradeID,
			&i.Quantidade,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsuario = `-- name: GetUsuario :one
SELECT id, empresa_id, nome, email, senha_hash, cargo, is_master, status, criado_em, atualizado_em FROM usuarios WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUsuario(ctx context.Context, id pgtype.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Cargo,
		&i.IsMaster,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id, empresa_id, nome, email, senha_hash, cargo, is_master, status, criado_em, atualizado_em FROM usuarios WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Cargo,
		&i.IsMaster,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getUsuarioPermissionForModule = `-- name: GetUsuarioPermissionForModule :one
SELECT usuario_id, modulo_id, pode_visualizar, pode_criar, pode_editar, pode_deletar FROM usuario_permissoes 
WHERE usuario_id = $1 AND modulo_id = $2 LIMIT 1
`

type GetUsuarioPermissionForModuleParams struct {
	UsuarioID pgtype.UUID
	ModuloID  string
}

func (q *Queries) GetUsuarioPermissionForModule(ctx context.Context, arg GetUsuarioPermissionForModuleParams) (UsuarioPermisso, error) {
	row := q.db.QueryRow(ctx, getUsuarioPermissionForModule, arg.UsuarioID, arg.ModuloID)
	var i UsuarioPermisso
	err := row.Scan(
		&i.UsuarioID,
		&i.ModuloID,
		&i.PodeVisualizar,
		&i.PodeCriar,
		&i.PodeEditar,
		&i.PodeDeletar,
	)
	return i, err
}

const getUsuarioPermissions = `-- name: GetUsuarioPermissions :many
SELECT usuario_id, modulo_id, pode_visualizar, pode_criar, pode_editar, pode_deletar FROM usuario_permissoes WHERE usuario_id = $1
`

func (q *Queries) GetUsuarioPermissions(ctx context.Context, usuarioID pgtype.UUID) ([]UsuarioPermisso, error) {
	rows, err := q.db.Query(ctx, getUsuarioPermissions, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsuarioPermisso
	for rows.Next() {
		var i UsuarioPermisso
		if err := rows.Scan(
			&i.UsuarioID,
			&i.ModuloID,
			&i.PodeVisualizar,
			&i.PodeCriar,
			&i.PodeEditar,
			&i.PodeDeletar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVendaByOfflineUUID = `-- name: GetVendaByOfflineUUID :one
SELECT id, empresa_id, total, status, forma_pagamento, chave_nfe, offline_uuid, criado_em FROM vendas WHERE offline_uuid = $1 LIMIT 1
`

func (q *Queries) GetVendaByOfflineUUID(ctx context.Context, offlineUuid pgtype.UUID) (Venda, error) {
	row := q.db.QueryRow(ctx, getVendaByOfflineUUID, offlineUuid)
	var i Venda
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Total,
		&i.Status,
		&i.FormaPagamento,
		&i.ChaveNfe,
		&i.OfflineUuid,
		&i.CriadoEm,
	)
	return i, err
}

const incrementEstoqueGrade = `-- name: IncrementEstoqueGrade :one
UPDATE produtos_grade
SET estoque_atual = estoque_atual + $2, preco_custo = $3
WHERE id = $1
RETURNING id, produto_id, sku, cor, tamanho, codigo_barras, estoque_atual, estoque_minimo, preco_venda, preco_custo, criado_em
`

type IncrementEstoqueGradeParams struct {
	ID           pgtype.UUID
	EstoqueAtual int32
	PrecoCusto   pgtype.Numeric
}

func (q *Queries) IncrementEstoqueGrade(ctx context.Context, arg IncrementEstoqueGradeParams) (ProdutosGrade, error) {
	row := q.db.QueryRow(ctx, incrementEstoqueGrade, arg.ID, arg.EstoqueAtual, arg.PrecoCusto)
	var i ProdutosGrade
	err := row.Scan(
		&i.ID,
		&i.ProdutoID,
		&i.Sku,
		&i.Cor,
		&i.Tamanho,
		&i.CodigoBarras,
		&i.EstoqueAtual,
		&i.EstoqueMinimo,
		&i.PrecoVenda,
		&i.PrecoCusto,
		&i.CriadoEm,
	)
	return i, err
}

const incrementarRealizadoPCO = `-- name: IncrementarRealizadoPCO :one
UPDATE pco_orcamentos
SET valor_realizado = valor_realizado + $4
WHERE empresa_id = $1 AND categoria = $2 AND mes_referencia = $3
RETURNING id, empresa_id, categoria, mes_referencia, limite_orcado, valor_realizado, criado_em
`

type IncrementarRealizadoPCOParams struct {
	EmpresaID      pgtype.UUID
	Categoria      string
	MesReferencia  string
	ValorRealizado pgtype.Numeric
}

func (q *Queries) IncrementarRealizadoPCO(ctx context.Context, arg IncrementarRealizadoPCOParams) (PcoOrcamento, error) {
	row := q.db.QueryRow(ctx, incrementarRealizadoPCO,
		arg.EmpresaID,
		arg.Categoria,
		arg.MesReferencia,
		arg.ValorRealizado,
	)
	var i PcoOrcamento
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Categoria,
		&i.MesReferencia,
		&i.LimiteOrcado,
		&i.ValorRealizado,
		&i.CriadoEm,
	)
	return i, err
}

const listBorderos = `-- name: ListBorderos :many
SELECT id, empresa_id, descricao, status, criado_em FROM borderos WHERE empresa_id = $1 ORDER BY criado_em DESC
`

func (q *Queries) ListBorderos(ctx context.Context, empresaID pgtype.UUID) ([]Bordero, error) {
	rows, err := q.db.Query(ctx, listBorderos, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bordero
	for rows.Next() {
		var i Bordero
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Descricao,
			&i.Status,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColaboradores = `-- name: ListColaboradores :many
SELECT id, empresa_id, nome, cpf, cargo, salario, data_admissao, status, facial_biometria_template, criado_em, atualizado_em FROM colaboradores WHERE empresa_id = $1
`

func (q *Queries) ListColaboradores(ctx context.Context, empresaID pgtype.UUID) ([]Colaboradore, error) {
	rows, err := q.db.Query(ctx, listColaboradores, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Colaboradore
	for rows.Next() {
		var i Colaboradore
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Nome,
			&i.Cpf,
			&i.Cargo,
			&i.Salario,
			&i.DataAdmissao,
			&i.Status,
			&i.FacialBiometriaTemplate,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComandasAbertas = `-- name: ListComandasAbertas :many
SELECT id, empresa_id, numero_mesa_comanda, total, status, criado_em, atualizado_em FROM comandas WHERE empresa_id = $1 AND status = 'ABERTA'
`

func (q *Queries) ListComandasAbertas(ctx context.Context, empresaID pgtype.UUID) ([]Comanda, error) {
	rows, err := q.db.Query(ctx, listComandasAbertas, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comanda
	for rows.Next() {
		var i Comanda
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.NumeroMesaComanda,
			&i.Total,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContasNoBorderop = `-- name: ListContasNoBorderop :many
SELECT id, empresa_id, borderop_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em FROM contas_pagar WHERE borderop_id = $1
`

func (q *Queries) ListContasNoBorderop(ctx context.Context, borderopID pgtype.UUID) ([]ContasPagar, error) {
	rows, err := q.db.Query(ctx, listContasNoBorderop, borderopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContasPagar
	for rows.Next() {
		var i ContasPagar
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.BorderopID,
			&i.Descricao,
			&i.Valor,
			&i.DataVencimento,
			&i.Status,
			&i.Origem,
			&i.OrigemID,
			&i.DataPagamento,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContasPagar = `-- name: ListContasPagar :many
SELECT id, empresa_id, borderop_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em FROM contas_pagar WHERE empresa_id = $1 ORDER BY data_vencimento ASC
`

func (q *Queries) ListContasPagar(ctx context.Context, empresaID pgtype.UUID) ([]ContasPagar, error) {
	rows, err := q.db.Query(ctx, listContasPagar, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContasPagar
	for rows.Next() {
		var i ContasPagar
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.BorderopID,
			&i.Descricao,
			&i.Valor,
			&i.DataVencimento,
			&i.Status,
			&i.Origem,
			&i.OrigemID,
			&i.DataPagamento,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContasReceber = `-- name: ListContasReceber :many
SELECT id, empresa_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em FROM contas_receber WHERE empresa_id = $1 ORDER BY data_vencimento ASC
`

func (q *Queries) ListContasReceber(ctx context.Context, empresaID pgtype.UUID) ([]ContasReceber, error) {
	rows, err := q.db.Query(ctx, listContasReceber, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContasReceber
	for rows.Next() {
		var i ContasReceber
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Descricao,
			&i.Valor,
			&i.DataVencimento,
			&i.Status,
			&i.Origem,
			&i.OrigemID,
			&i.DataPagamento,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItensKdsPendentes = `-- name: ListItensKdsPendentes :many
SELECT ci.id, ci.comanda_id, ci.produto_grade_id, ci.quantidade, ci.preco_unitario, ci.status_cozinha, ci.criado_em, pg.sku, p.nome as produto_nome, c.numero_mesa_comanda 
FROM comanda_itens ci
JOIN comandas c ON ci.comanda_id = c.id
JOIN produtos_grade pg ON ci.produto_grade_id = pg.id
JOIN produtos p ON pg.produto_id = p.id
WHERE c.empresa_id = $1 AND ci.status_cozinha IN ('PENDENTE', 'EM_PREPARO')
ORDER BY ci.criado_em ASC
`

type ListItensKdsPendentesRow struct {
	ID                pgtype.UUID
	ComandaID         pgtype.UUID
	ProdutoGradeID    pgtype.UUID
	Quantidade        int32
	PrecoUnitario     pgtype.Numeric
	StatusCozinha     string
	CriadoEm          pgtype.Timestamp
	Sku               string
	ProdutoNome       string
	NumeroMesaComanda string
}

func (q *Queries) ListItensKdsPendentes(ctx context.Context, empresaID pgtype.UUID) ([]ListItensKdsPendentesRow, error) {
	rows, err := q.db.Query(ctx, listItensKdsPendentes, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItensKdsPendentesRow
	for rows.Next() {
		var i ListItensKdsPendentesRow
		if err := rows.Scan(
			&i.ID,
			&i.ComandaID,
			&i.ProdutoGradeID,
			&i.Quantidade,
			&i.PrecoUnitario,
			&i.StatusCozinha,
			&i.CriadoEm,
			&i.Sku,
			&i.ProdutoNome,
			&i.NumeroMesaComanda,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotasFiscais = `-- name: ListNotasFiscais :many
SELECT id, empresa_id, tipo, chave_acesso, numero, serie, valor_total, xml_content, status, criado_em FROM notas_fiscais WHERE empresa_id = $1 ORDER BY criado_em DESC
`

func (q *Queries) ListNotasFiscais(ctx context.Context, empresaID pgtype.UUID) ([]NotasFiscai, error) {
	rows, err := q.db.Query(ctx, listNotasFiscais, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotasFiscai
	for rows.Next() {
		var i NotasFiscai
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Tipo,
			&i.ChaveAcesso,
			&i.Numero,
			&i.Serie,
			&i.ValorTotal,
			&i.XmlContent,
			&i.Status,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotasPendentesFila = `-- name: ListNotasPendentesFila :many
SELECT nff.id, nff.nota_fiscal_id, nff.status, nff.tentativas, nff.erro_log, nff.criado_em, nff.atualizado_em, nf.xml_content, nf.tipo, nf.valor_total, nf.empresa_id FROM notas_fiscais_fila nff
JOIN notas_fiscais nf ON nff.nota_fiscal_id = nf.id
WHERE nff.status = 'AGUARDANDO_ENVIO' AND nff.tentativas < 5
`

type ListNotasPendentesFilaRow struct {
	ID           pgtype.UUID
	NotaFiscalID pgtype.UUID
	Status       string
	Tentativas   int32
	ErroLog      pgtype.Text
	CriadoEm     pgtype.Timestamp
	AtualizadoEm pgtype.Timestamp
	XmlContent   string
	Tipo         string
	ValorTotal   pgtype.Numeric
	EmpresaID    pgtype.UUID
}

func (q *Queries) ListNotasPendentesFila(ctx context.Context) ([]ListNotasPendentesFilaRow, error) {
	rows, err := q.db.Query(ctx, listNotasPendentesFila)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotasPendentesFilaRow
	for rows.Next() {
		var i ListNotasPendentesFilaRow
		if err := rows.Scan(
			&i.ID,
			&i.NotaFiscalID,
			&i.Status,
			&i.Tentativas,
			&i.ErroLog,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.XmlContent,
			&i.Tipo,
			&i.ValorTotal,
			&i.EmpresaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrcamentosForSolicitacao = `-- name: ListOrcamentosForSolicitacao :many
SELECT id, empresa_id, solicitacao_compra_id, fornecedor_nome, valor_total, prazo_entrega_dias, escolhido, criado_em FROM orcamentos_fornecedores WHERE solicitacao_compra_id = $1
`

func (q *Queries) ListOrcamentosForSolicitacao(ctx context.Context, solicitacaoCompraID pgtype.UUID) ([]OrcamentosFornecedore, error) {
	rows, err := q.db.Query(ctx, listOrcamentosForSolicitacao, solicitacaoCompraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrcamentosFornecedore
	for rows.Next() {
		var i OrcamentosFornecedore
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.SolicitacaoCompraID,
			&i.FornecedorNome,
			&i.ValorTotal,
			&i.PrazoEntregaDias,
			&i.Escolhido,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdensServico = `-- name: ListOrdensServico :many
SELECT id, empresa_id, cliente_nome, veiculo_equipamento, status, total_pecas, total_mao_obra, total_geral, criado_em, atualizado_em FROM ordens_servico WHERE empresa_id = $1 ORDER BY criado_em DESC
`

func (q *Queries) ListOrdensServico(ctx context.Context, empresaID pgtype.UUID) ([]OrdensServico, error) {
	rows, err := q.db.Query(ctx, listOrdensServico, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdensServico
	for rows.Next() {
		var i OrdensServico
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.ClienteNome,
			&i.VeiculoEquipamento,
			&i.Status,
			&i.TotalPecas,
			&i.TotalMaoObra,
			&i.TotalGeral,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPcoOrcamentos = `-- name: ListPcoOrcamentos :many
SELECT id, empresa_id, categoria, mes_referencia, limite_orcado, valor_realizado, criado_em FROM pco_orcamentos 
WHERE empresa_id = $1 AND mes_referencia = $2
`

type ListPcoOrcamentosParams struct {
	EmpresaID     pgtype.UUID
	MesReferencia string
}

func (q *Queries) ListPcoOrcamentos(ctx context.Context, arg ListPcoOrcamentosParams) ([]PcoOrcamento, error) {
	rows, err := q.db.Query(ctx, listPcoOrcamentos, arg.EmpresaID, arg.MesReferencia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PcoOrcamento
	for rows.Next() {
		var i PcoOrcamento
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Categoria,
			&i.MesReferencia,
			&i.LimiteOrcado,
			&i.ValorRealizado,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProdutos = `-- name: ListProdutos :many
SELECT id, empresa_id, nome, descricao, sku_pai, criado_em FROM produtos WHERE empresa_id = $1
`

func (q *Queries) ListProdutos(ctx context.Context, empresaID pgtype.UUID) ([]Produto, error) {
	rows, err := q.db.Query(ctx, listProdutos, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Produto
	for rows.Next() {
		var i Produto
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Nome,
			&i.Descricao,
			&i.SkuPai,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProdutosAbaixoEstoqueMinimo = `-- name: ListProdutosAbaixoEstoqueMinimo :many
SELECT pg.id, pg.produto_id, pg.sku, pg.cor, pg.tamanho, pg.codigo_barras, pg.estoque_atual, pg.estoque_minimo, pg.preco_venda, pg.preco_custo, pg.criado_em, p.nome as produto_nome FROM produtos_grade pg
JOIN produtos p ON pg.produto_id = p.id
WHERE p.empresa_id = $1 AND pg.estoque_atual <= pg.estoque_minimo
`

type ListProdutosAbaixoEstoqueMinimoRow struct {
	ID            pgtype.UUID
	ProdutoID     pgtype.UUID
	Sku           string
	Cor           pgtype.Text
	Tamanho       pgtype.Text
	CodigoBarras  pgtype.Text
	EstoqueAtual  int32
	EstoqueMinimo int32
	PrecoVenda    pgtype.Numeric
	PrecoCusto    pgtype.Numeric
	CriadoEm      pgtype.Timestamp
	ProdutoNome   string
}

func (q *Queries) ListProdutosAbaixoEstoqueMinimo(ctx context.Context, empresaID pgtype.UUID) ([]ListProdutosAbaixoEstoqueMinimoRow, error) {
	rows, err := q.db.Query(ctx, listProdutosAbaixoEstoqueMinimo, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProdutosAbaixoEstoqueMinimoRow
	for rows.Next() {
		var i ListProdutosAbaixoEstoqueMinimoRow
		if err := rows.Scan(
			&i.ID,
			&i.ProdutoID,
			&i.Sku,
			&i.Cor,
			&i.Tamanho,
			&i.CodigoBarras,
			&i.EstoqueAtual,
			&i.EstoqueMinimo,
			&i.PrecoVenda,
			&i.PrecoCusto,
			&i.CriadoEm,
			&i.ProdutoNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProdutosGrade = `-- name: ListProdutosGrade :many
SELECT pg.id, pg.produto_id, pg.sku, pg.cor, pg.tamanho, pg.codigo_barras, pg.estoque_atual, pg.estoque_minimo, pg.preco_venda, pg.preco_custo, pg.criado_em FROM produtos_grade pg
JOIN produtos p ON pg.produto_id = p.id
WHERE p.empresa_id = $1
`

func (q *Queries) ListProdutosGrade(ctx context.Context, empresaID pgtype.UUID) ([]ProdutosGrade, error) {
	rows, err := q.db.Query(ctx, listProdutosGrade, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProdutosGrade
	for rows.Next() {
		var i ProdutosGrade
		if err := rows.Scan(
			&i.ID,
			&i.ProdutoID,
			&i.Sku,
			&i.Cor,
			&i.Tamanho,
			&i.CodigoBarras,
			&i.EstoqueAtual,
			&i.EstoqueMinimo,
			&i.PrecoVenda,
			&i.PrecoCusto,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProdutosGradeParaSync = `-- name: ListProdutosGradeParaSync :many
SELECT pg.id as produto_grade_id, pg.sku, pg.cor, pg.tamanho, pg.codigo_barras, pg.preco_venda, pg.preco_custo, pg.estoque_atual, pg.estoque_minimo, p.nome as produto_nome, p.descricao as produto_descricao
FROM produtos_grade pg
JOIN produtos p ON pg.produto_id = p.id
WHERE p.empresa_id = $1
`

type ListProdutosGradeParaSyncRow struct {
	ProdutoGradeID   pgtype.UUID
	Sku              string
	Cor              pgtype.Text
	Tamanho          pgtype.Text
	CodigoBarras     pgtype.Text
	PrecoVenda       pgtype.Numeric
	PrecoCusto       pgtype.Numeric
	EstoqueAtual     int32
	EstoqueMinimo    int32
	ProdutoNome      string
	ProdutoDescricao pgtype.Text
}

func (q *Queries) ListProdutosGradeParaSync(ctx context.Context, empresaID pgtype.UUID) ([]ListProdutosGradeParaSyncRow, error) {
	rows, err := q.db.Query(ctx, listProdutosGradeParaSync, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProdutosGradeParaSyncRow
	for rows.Next() {
		var i ListProdutosGradeParaSyncRow
		if err := rows.Scan(
			&i.ProdutoGradeID,
			&i.Sku,
			&i.Cor,
			&i.Tamanho,
			&i.CodigoBarras,
			&i.PrecoVenda,
			&i.PrecoCusto,
			&i.EstoqueAtual,
			&i.EstoqueMinimo,
			&i.ProdutoNome,
			&i.ProdutoDescricao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemAuditLogs = `-- name: ListSystemAuditLogs :many
SELECT las.id, las.empresa_id, las.usuario_id, las.impersonator_id, las.acao, las.detalhes, las.criado_em, u.nome as usuario_nome, e.razao_social as empresa_nome 
FROM logs_auditoria_sistema las
JOIN usuarios u ON las.usuario_id = u.id
JOIN empresas e ON las.empresa_id = e.id
ORDER BY las.criado_em DESC
`

type ListSystemAuditLogsRow struct {
	ID             pgtype.UUID
	EmpresaID      pgtype.UUID
	UsuarioID      pgtype.UUID
	ImpersonatorID pgtype.UUID
	Acao           string
	Detalhes       pgtype.Text
	CriadoEm       pgtype.Timestamp
	UsuarioNome    string
	EmpresaNome    string
}

func (q *Queries) ListSystemAuditLogs(ctx context.Context) ([]ListSystemAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listSystemAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemAuditLogsRow
	for rows.Next() {
		var i ListSystemAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.UsuarioID,
			&i.ImpersonatorID,
			&i.Acao,
			&i.Detalhes,
			&i.CriadoEm,
			&i.UsuarioNome,
			&i.EmpresaNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrcamentoComoEscolhido = `-- name: MarkOrcamentoComoEscolhido :one
UPDATE orcamentos_fornecedores
SET escolhido = TRUE
WHERE id = $1
RETURNING id, empresa_id, solicitacao_compra_id, fornecedor_nome, valor_total, prazo_entrega_dias, escolhido, criado_em
`

func (q *Queries) MarkOrcamentoComoEscolhido(ctx context.Context, id pgtype.UUID) (OrcamentosFornecedore, error) {
	row := q.db.QueryRow(ctx, markOrcamentoComoEscolhido, id)
	var i OrcamentosFornecedore
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.SolicitacaoCompraID,
		&i.FornecedorNome,
		&i.ValorTotal,
		&i.PrazoEntregaDias,
		&i.Escolhido,
		&i.CriadoEm,
	)
	return i, err
}

const saveBankConfig = `-- name: SaveBankConfig :one
INSERT INTO configuracoes_banco (
    empresa_id, banco_nome, client_id, client_secret, certificado_digital, token_atual, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (empresa_id, banco_nome) DO UPDATE
SET client_id = EXCLUDED.client_id,
    client_secret = EXCLUDED.client_secret,
    certificado_digital = EXCLUDED.certificado_digital,
    token_atual = EXCLUDED.token_atual,
    status = EXCLUDED.status
RETURNING id, empresa_id, banco_nome, client_id, client_secret, certificado_digital, token_atual, status, criado_em
`

type SaveBankConfigParams struct {
	EmpresaID          pgtype.UUID
	BancoNome          string
	ClientID           string
	ClientSecret       string
	CertificadoDigital pgtype.Text
	TokenAtual         pgtype.Text
	Status             string
}

func (q *Queries) SaveBankConfig(ctx context.Context, arg SaveBankConfigParams) (ConfiguracoesBanco, error) {
	row := q.db.QueryRow(ctx, saveBankConfig,
		arg.EmpresaID,
		arg.BancoNome,
		arg.ClientID,
		arg.ClientSecret,
		arg.CertificadoDigital,
		arg.TokenAtual,
		arg.Status,
	)
	var i ConfiguracoesBanco
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.BancoNome,
		&i.ClientID,
		&i.ClientSecret,
		&i.CertificadoDigital,
		&i.TokenAtual,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const setUsuarioPermission = `-- name: SetUsuarioPermission :one
INSERT INTO usuario_permissoes (
    usuario_id, modulo_id, pode_visualizar, pode_criar, pode_editar, pode_deletar
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (usuario_id, modulo_id) DO UPDATE
SET 
    pode_visualizar = EXCLUDED.pode_visualizar,
    pode_criar = EXCLUDED.pode_criar,
    pode_editar = EXCLUDED.pode_editar,
    pode_deletar = EXCLUDED.pode_deletar
RETURNING usuario_id, modulo_id, pode_visualizar, pode_criar, pode_editar, pode_deletar
`

type SetUsuarioPermissionParams struct {
	UsuarioID      pgtype.UUID
	ModuloID       string
	PodeVisualizar pgtype.Bool
	PodeCriar      pgtype.Bool
	PodeEditar     pgtype.Bool
	PodeDeletar    pgtype.Bool
}

func (q *Queries) SetUsuarioPermission(ctx context.Context, arg SetUsuarioPermissionParams) (UsuarioPermisso, error) {
	row := q.db.QueryRow(ctx, setUsuarioPermission,
		arg.UsuarioID,
		arg.ModuloID,
		arg.PodeVisualizar,
		arg.PodeCriar,
		arg.PodeEditar,
		arg.PodeDeletar,
	)
	var i UsuarioPermisso
	err := row.Scan(
		&i.UsuarioID,
		&i.ModuloID,
		&i.PodeVisualizar,
		&i.PodeCriar,
		&i.PodeEditar,
		&i.PodeDeletar,
	)
	return i, err
}

const updateBorderopStatus = `-- name: UpdateBorderopStatus :one
UPDATE borderos
SET status = $2
WHERE id = $1
RETURNING id, empresa_id, descricao, status, criado_em
`

type UpdateBorderopStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateBorderopStatus(ctx context.Context, arg UpdateBorderopStatusParams) (Bordero, error) {
	row := q.db.QueryRow(ctx, updateBorderopStatus, arg.ID, arg.Status)
	var i Bordero
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Descricao,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const updateColaboradorFaceTemplate = `-- name: UpdateColaboradorFaceTemplate :one
UPDATE colaboradores
SET facial_biometria_template = $2, atualizado_em = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, empresa_id, nome, cpf, cargo, salario, data_admissao, status, facial_biometria_template, criado_em, atualizado_em
`

type UpdateColaboradorFaceTemplateParams struct {
	ID                      pgtype.UUID
	FacialBiometriaTemplate pgtype.Text
}

func (q *Queries) UpdateColaboradorFaceTemplate(ctx context.Context, arg UpdateColaboradorFaceTemplateParams) (Colaboradore, error) {
	row := q.db.QueryRow(ctx, updateColaboradorFaceTemplate, arg.ID, arg.FacialBiometriaTemplate)
	var i Colaboradore
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Cpf,
		&i.Cargo,
		&i.Salario,
		&i.DataAdmissao,
		&i.Status,
		&i.FacialBiometriaTemplate,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updateComandaStatus = `-- name: UpdateComandaStatus :one
UPDATE comandas
SET status = $2, atualizado_em = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, empresa_id, numero_mesa_comanda, total, status, criado_em, atualizado_em
`

type UpdateComandaStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateComandaStatus(ctx context.Context, arg UpdateComandaStatusParams) (Comanda, error) {
	row := q.db.QueryRow(ctx, updateComandaStatus, arg.ID, arg.Status)
	var i Comanda
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.NumeroMesaComanda,
		&i.Total,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updateComandaTotal = `-- name: UpdateComandaTotal :one
UPDATE comandas
SET total = $2, atualizado_em = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, empresa_id, numero_mesa_comanda, total, status, criado_em, atualizado_em
`

type UpdateComandaTotalParams struct {
	ID    pgtype.UUID
	Total pgtype.Numeric
}

func (q *Queries) UpdateComandaTotal(ctx context.Context, arg UpdateComandaTotalParams) (Comanda, error) {
	row := q.db.QueryRow(ctx, updateComandaTotal, arg.ID, arg.Total)
	var i Comanda
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.NumeroMesaComanda,
		&i.Total,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updateContaPagarStatus = `-- name: UpdateContaPagarStatus :one
UPDATE contas_pagar
SET status = $2, data_pagamento = $3
WHERE id = $1
RETURNING id, empresa_id, borderop_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em
`

type UpdateContaPagarStatusParams struct {
	ID            pgtype.UUID
	Status        string
	DataPagamento pgtype.Timestamp
}

func (q *Queries) UpdateContaPagarStatus(ctx context.Context, arg UpdateContaPagarStatusParams) (ContasPagar, error) {
	row := q.db.QueryRow(ctx, updateContaPagarStatus, arg.ID, arg.Status, arg.DataPagamento)
	var i ContasPagar
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.BorderopID,
		&i.Descricao,
		&i.Valor,
		&i.DataVencimento,
		&i.Status,
		&i.Origem,
		&i.OrigemID,
		&i.DataPagamento,
		&i.CriadoEm,
	)
	return i, err
}

const updateContaReceberStatus = `-- name: UpdateContaReceberStatus :one
UPDATE contas_receber
SET status = $2, data_pagamento = $3
WHERE id = $1
RETURNING id, empresa_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em
`

type UpdateContaReceberStatusParams struct {
	ID            pgtype.UUID
	Status        string
	DataPagamento pgtype.Timestamp
}

func (q *Queries) UpdateContaReceberStatus(ctx context.Context, arg UpdateContaReceberStatusParams) (ContasReceber, error) {
	row := q.db.QueryRow(ctx, updateContaReceberStatus, arg.ID, arg.Status, arg.DataPagamento)
	var i ContasReceber
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Descricao,
		&i.Valor,
		&i.DataVencimento,
		&i.Status,
		&i.Origem,
		&i.OrigemID,
		&i.DataPagamento,
		&i.CriadoEm,
	)
	return i, err
}

const updateEmpresaAddons = `-- name: UpdateEmpresaAddons :one
UPDATE empresas
SET 
    modulo_rh = $2,
    modulo_kds = $3,
    modulo_mesas_comandas = $4,
    modulo_ordem_servico = $5,
    modulo_grade_produtos = $6,
    modulo_self_checkout = $7,
    atualizado_em = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, razao_social, cnpj, nicho, modulo_rh, modulo_kds, modulo_mesas_comandas, modulo_ordem_servico, modulo_grade_produtos, modulo_self_checkout, modulo_ponto_facial, status, criado_em, atualizado_em
`

type UpdateEmpresaAddonsParams struct {
	ID                  pgtype.UUID
	ModuloRh            pgtype.Bool
	ModuloKds           pgtype.Bool
	ModuloMesasComandas pgtype.Bool
	ModuloOrdemServico  pgtype.Bool
	ModuloGradeProdutos pgtype.Bool
	ModuloSelfCheckout  pgtype.Bool
}

func (q *Queries) UpdateEmpresaAddons(ctx context.Context, arg UpdateEmpresaAddonsParams) (Empresa, error) {
	row := q.db.QueryRow(ctx, updateEmpresaAddons,
		arg.ID,
		arg.ModuloRh,
		arg.ModuloKds,
		arg.ModuloMesasComandas,
		arg.ModuloOrdemServico,
		arg.ModuloGradeProdutos,
		arg.ModuloSelfCheckout,
	)
	var i Empresa
	err := row.Scan(
		&i.ID,
		&i.RazaoSocial,
		&i.Cnpj,
		&i.Nicho,
		&i.ModuloRh,
		&i.ModuloKds,
		&i.ModuloMesasComandas,
		&i.ModuloOrdemServico,
		&i.ModuloGradeProdutos,
		&i.ModuloSelfCheckout,
		&i.ModuloPontoFacial,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updateFilaStatus = `-- name: UpdateFilaStatus :one
UPDATE notas_fiscais_fila
SET status = $2, tentativas = tentativas + 1, erro_log = $3, atualizado_em = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, nota_fiscal_id, status, tentativas, erro_log, criado_em, atualizado_em
`

type UpdateFilaStatusParams struct {
	ID      pgtype.UUID
	Status  string
	ErroLog pgtype.Text
}

func (q *Queries) UpdateFilaStatus(ctx context.Context, arg UpdateFilaStatusParams) (NotasFiscaisFila, error) {
	row := q.db.QueryRow(ctx, updateFilaStatus, arg.ID, arg.Status, arg.ErroLog)
	var i NotasFiscaisFila
	err := row.Scan(
		&i.ID,
		&i.NotaFiscalID,
		&i.Status,
		&i.Tentativas,
		&i.ErroLog,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updateFolhaStatus = `-- name: UpdateFolhaStatus :one
UPDATE folhas_pagamento
SET status = $2
WHERE id = $1
RETURNING id, empresa_id, mes_referencia, status, total_proventos, total_descontos, total_liquido, criado_em
`

type UpdateFolhaStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateFolhaStatus(ctx context.Context, arg UpdateFolhaStatusParams) (FolhasPagamento, error) {
	row := q.db.QueryRow(ctx, updateFolhaStatus, arg.ID, arg.Status)
	var i FolhasPagamento
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.MesReferencia,
		&i.Status,
		&i.TotalProventos,
		&i.TotalDescontos,
		&i.TotalLiquido,
		&i.CriadoEm,
	)
	return i, err
}

const updateKdsStatusItem = `-- name: UpdateKdsStatusItem :one
UPDATE comanda_itens
SET status_cozinha = $2
WHERE id = $1
RETURNING id, comanda_id, produto_grade_id, quantidade, preco_unitario, status_cozinha, criado_em
`

type UpdateKdsStatusItemParams struct {
	ID            pgtype.UUID
	StatusCozinha string
}

func (q *Queries) UpdateKdsStatusItem(ctx context.Context, arg UpdateKdsStatusItemParams) (ComandaIten, error) {
	row := q.db.QueryRow(ctx, updateKdsStatusItem, arg.ID, arg.StatusCozinha)
	var i ComandaIten
	err := row.Scan(
		&i.ID,
		&i.ComandaID,
		&i.ProdutoGradeID,
		&i.Quantidade,
		&i.PrecoUnitario,
		&i.StatusCozinha,
		&i.CriadoEm,
	)
	return i, err
}

const updateNotaFiscalStatus = `-- name: UpdateNotaFiscalStatus :one
UPDATE notas_fiscais
SET status = $2
WHERE id = $1
RETURNING id, empresa_id, tipo, chave_acesso, numero, serie, valor_total, xml_content, status, criado_em
`

type UpdateNotaFiscalStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateNotaFiscalStatus(ctx context.Context, arg UpdateNotaFiscalStatusParams) (NotasFiscai, error) {
	row := q.db.QueryRow(ctx, updateNotaFiscalStatus, arg.ID, arg.Status)
	var i NotasFiscai
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Tipo,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ValorTotal,
		&i.XmlContent,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const updateOSStatus = `-- name: UpdateOSStatus :one
UPDATE ordens_servico
SET status = $2, total_pecas = $3, total_mao_obra = $4, total_geral = $5, atualizado_em = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, empresa_id, cliente_nome, veiculo_equipamento, status, total_pecas, total_mao_obra, total_geral, criado_em, atualizado_em
`

type UpdateOSStatusParams struct {
	ID           pgtype.UUID
	Status       string
	TotalPecas   pgtype.Numeric
	TotalMaoObra pgtype.Numeric
	TotalGeral   pgtype.Numeric
}

func (q *Queries) UpdateOSStatus(ctx context.Context, arg UpdateOSStatusParams) (OrdensServico, error) {
	row := q.db.QueryRow(ctx, updateOSStatus,
		arg.ID,
		arg.Status,
		arg.TotalPecas,
		arg.TotalMaoObra,
		arg.TotalGeral,
	)
	var i OrdensServico
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ClienteNome,
		&i.VeiculoEquipamento,
		&i.Status,
		&i.TotalPecas,
		&i.TotalMaoObra,
		&i.TotalGeral,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updatePedidoCompraStatus = `-- name: UpdatePedidoCompraStatus :one
UPDATE pedidos_compra
SET status = $2
WHERE id = $1
RETURNING id, empresa_id, solicitacao_compra_id, fornecedor_nome, status, total, criado_em
`

type UpdatePedidoCompraStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdatePedidoCompraStatus(ctx context.Context, arg UpdatePedidoCompraStatusParams) (PedidosCompra, error) {
	row := q.db.QueryRow(ctx, updatePedidoCompraStatus, arg.ID, arg.Status)
	var i PedidosCompra
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.SolicitacaoCompraID,
		&i.FornecedorNome,
		&i.Status,
		&i.Total,
		&i.CriadoEm,
	)
	return i, err
}

const updateSolicitacaoCompraStatus = `-- name: UpdateSolicitacaoCompraStatus :one
UPDATE solicitacoes_compra
SET status = $2
WHERE id = $1
RETURNING id, empresa_id, usuario_id, status, observacoes, criado_em
`

type UpdateSolicitacaoCompraStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateSolicitacaoCompraStatus(ctx context.Context, arg UpdateSolicitacaoCompraStatusParams) (SolicitacoesCompra, error) {
	row := q.db.QueryRow(ctx, updateSolicitacaoCompraStatus, arg.ID, arg.Status)
	var i SolicitacoesCompra
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.UsuarioID,
		&i.Status,
		&i.Observacoes,
		&i.CriadoEm,
	)
	return i, err
}

const vincularContaAoBorderop = `-- name: VincularContaAoBorderop :one
UPDATE contas_pagar
SET borderop_id = $2
WHERE id = $1 AND empresa_id = $3
RETURNING id, empresa_id, borderop_id, descricao, valor, data_vencimento, status, origem, origem_id, data_pagamento, criado_em
`

type VincularContaAoBorderopParams struct {
	ID         pgtype.UUID
	BorderopID pgtype.UUID
	EmpresaID  pgtype.UUID
}

func (q *Queries) VincularContaAoBorderop(ctx context.Context, arg VincularContaAoBorderopParams) (ContasPagar, error) {
	row := q.db.QueryRow(ctx, vincularContaAoBorderop, arg.ID, arg.BorderopID, arg.EmpresaID)
	var i ContasPagar
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.BorderopID,
		&i.Descricao,
		&i.Valor,
		&i.DataVencimento,
		&i.Status,
		&i.Origem,
		&i.OrigemID,
		&i.DataPagamento,
		&i.CriadoEm,
	)
	return i, err
}
